import Foundation

/// User-facing names for the bundled icon resources; persisted IDs stay unchanged.
/// Source: https://github.com/lobehub/lobe-icons#readme
/// Parenthetical provider notes are omitted in the compact picker.
enum MCPIconDisplayNames {
    static let byID: [String: String] = [
        "ace": "ACE",
        "adobe": "Adobe",
        "adobefirefly": "Adobe Firefly",
        "agui": "AG-UI",
        "amp": "Amp",
        "antigravity": "Antigravity",
        "automatic": "Automatic1111",
        "bilibiliindex": "Bilibili Index",
        "bing": "Microsoft Bing",
        "brave": "Brave",
        "capcut": "CapCut",
        "cherrystudio": "Cherry Studio",
        "claudecode": "Claude Code",
        "cline": "Cline",
        "clipdrop": "Clipdrop",
        "cloudflare": "Cloudflare",
        "codeflicker": "CodeFlicker",
        "codegeex": "CodeGeeX",
        "cogvideo": "CogVideo",
        "cogview": "CogView",
        "colab": "Colab",
        "comfyui": "ComfyUI",
        "context7": "Context7",
        "copilot": "Microsoft Copilot",
        "copilotkit": "CopilotKit",
        "coqui": "Coqui",
        "coze": "Coze",
        "crewai": "CrewAI",
        "cursor": "Cursor",
        "cybercut": "CyberCut",
        "dalle": "DALL·E",
        "deepl": "DeepL",
        "dify": "Dify",
        "doc2x": "Doc2X",
        "docsearch": "DocSearch",
        "dreammachine": "DreamMachine",
        "elevenlabs": "ElevenLabs",
        "elevenx": "11x",
        "exa": "Exa",
        "fastgpt": "FastGPT",
        "figma": "Figma",
        "firecrawl": "Firecrawl",
        "fishaudio": "FishAudio",
        "flowith": "Flowith",
        "flux": "Flux",
        "github": "GitHub",
        "glif": "Glif",
        "goose": "Goose",
        "gradio": "Gradio",
        "greptile": "Greptile",
        "haiper": "Haiper",
        "hedra": "Hedra",
        "huggingface": "Hugging Face",
        "ideogram": "Ideogram",
        "jimeng": "Jimeng",
        "jina": "Jina",
        "junie": "Junie",
        "kilocode": "Kilo Code",
        "kling": "Kling",
        "kolors": "Kolors",
        "krea": "Krea",
        "langchain": "LangChain",
        "langfuse": "Langfuse",
        "langgraph": "LangGraph",
        "langsmith": "LangSmith",
        "lightricks": "Lightricks",
        "linear": "Linear",
        "livekit": "LiveKit",
        "llamaindex": "LlamaIndex",
        "longcat": "LongCat",
        "lovable": "Lovable",
        "lovart": "Lovart",
        "luma": "Luma",
        "magic": "Magic",
        "make": "Make",
        "manus": "Manus",
        "mastra": "Mastra",
        "mcp": "MCP",
        "mcpso": "MCP.so",
        "metagpt": "MetaGPT",
        "midjourney": "Midjourney",
        "morph": "Morph",
        "myshell": "MyShell",
        "n8n": "n8n",
        "nanobanana": "Nano Banana",
        "notebooklm": "NotebookLM",
        "notion": "Notion",
        "novelai": "NovelAI",
        "openclaw": "OpenClaw",
        "opencode": "opencode",
        "openhands": "OpenHands",
        "openwebui": "OpenWebUI",
        "parallel": "Parallel",
        "perplexity": "Perplexity",
        "phidata": "Phidata",
        "phind": "Phind",
        "pika": "Pika",
        "pixverse": "PixVerse",
        "playwright": "Playwright",
        "poe": "Poe",
        "pollinations": "Pollinations",
        "pydanticai": "PydanticAI",
        "railway": "Railway",
        "recraft": "Recraft",
        "relace": "Relace",
        "replit": "Replit",
        "roocode": "RooCode",
        "rsshub": "RSSHub",
        "runway": "Runway",
        "sentry": "Sentry",
        "slack": "Slack",
        "smithery": "Smithery",
        "sora": "Sora",
        "stripe": "Stripe",
        "suno": "Suno",
        "supabase": "Supabase",
        "sync": "Sync",
        "tavily": "Tavily",
        "tinyfish": "TinyFish",
        "topazlabs": "TopazLabs",
        "trae": "TRAE",
        "tripo": "Tripo",
        "turix": "TuriX",
        "udio": "Udio",
        "unstructured": "Unstructured",
        "v0": "V0",
        "vectorizerai": "Vectorizer.AI",
        "vidu": "Vidu",
        "viggle": "Viggle",
        "windsurf": "Windsurf",
        "zapier": "Zapier",
        "zeabur": "Zeabur",
        "zencoder": "Zencoder",
    ]
}
