import Foundation

extension ModelCatalog {
    static let mistralRecords: [Record] = [
        // Seeded — appear in the model picker on first launch
        // Mistral Medium 3.5 is seeded as the legacy short alias `mistral-medium-3.5` below.
        Record(id: "mistral-medium-3-5-26-04", displayName: "Mistral Medium 3.5",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "mistral-large-3-25-12", displayName: "Mistral Large 3",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "mistral-small-4-0-26-03", displayName: "Mistral Small 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "magistral-medium-1-2-25-09", displayName: "Magistral Medium",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        // Catalog-only — recognized when fetched via the API
        Record(id: "mistral-medium-3-1-25-08", displayName: "Mistral Medium 3.1",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "ministral-3-14b-25-12", displayName: "Ministral 3 14B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "ministral-3-8b-25-12", displayName: "Ministral 3 8B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "ministral-3-3b-25-12", displayName: "Ministral 3 3B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "devstral-2-25-12", displayName: "Devstral 2",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 256_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "codestral-25-08", displayName: "Codestral",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 256_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        // Back-compat alias for the old short ID Jin previously seeded — keeps reasoning toggle
        // available for chats already pinned to this ID.
        Record(id: "mistral-medium-3.5", displayName: "Mistral Medium 3.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
    ]
}
