import Foundation

// MARK: - Independent Provider Records

extension ModelCatalog {

    // MARK: Anthropic

    static let anthropicRecords: [Record] = [
        // Fable/Mythos 5 generation: most capable widely released model. Adaptive thinking is
        // always on (no disabled config), no sampling params, effort low…max. Server-side
        // tools (web search, web fetch, code execution) are not supported at launch, so
        // `.codeExecution` is intentionally omitted. Mythos 5 shares the exact surface but is
        // limited-availability (Project Glasswing), so it is recognized-but-not-seeded.
        Record(id: "claude-fable-5", displayName: "Claude Fable 5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-mythos-5", displayName: "Claude Mythos 5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "claude-opus-4-8", displayName: "Claude Opus 4.8",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-opus-4-7", displayName: "Claude Opus 4.7",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-opus-4-6", displayName: "Claude Opus 4.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        // Sonnet 5: best speed/intelligence combination in the Sonnet tier, near-Opus quality
        // on coding and agentic work. Adaptive thinking (with explicit disable — unlike Fable 5,
        // omitting `thinking` on Sonnet 5 defaults to adaptive-on, not off). Full effort range
        // low...max (first Sonnet-tier model with xhigh). Unlike Fable 5/Mythos 5, Sonnet 5 DOES
        // support server-side code execution and web search (incl. dynamic filtering) at launch.
        Record(id: "claude-sonnet-5", displayName: "Claude Sonnet 5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-sonnet-4-6", displayName: "Claude Sonnet 4.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_000_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-opus-4-5-20251101", displayName: "Claude Opus 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-sonnet-4-5-20250929", displayName: "Claude Sonnet 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-haiku-4-5-20251001", displayName: "Claude Haiku 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-opus-4-1-20250805", displayName: "Claude Opus 4.1",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               maxOutputTokens: 32_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "claude-opus-4-20250514", displayName: "Claude Opus 4 (Legacy)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               maxOutputTokens: 32_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: false, isSeeded: false),
        Record(id: "claude-sonnet-4-20250514", displayName: "Claude Sonnet 4 (Legacy)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        Record(id: "claude-opus-4", displayName: "Claude Opus 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "claude-sonnet-4", displayName: "Claude Sonnet 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "claude-haiku-4", displayName: "Claude Haiku 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 200_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: Perplexity

    static let perplexityRecords: [Record] = [
        // Seeded (capabilities match DefaultProviderSeeds; nativePDF added per JinModelSupport)
        Record(id: "sonar", displayName: "Sonar",
               capabilities: [.streaming, .vision, .nativePDF],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: true),
        Record(id: "sonar-pro", displayName: "Sonar Pro",
               capabilities: [.streaming, .toolCalling, .vision, .nativePDF],
               contextWindow: 200_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "sonar-reasoning-pro", displayName: "Sonar Reasoning Pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .nativePDF],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "sonar-deep-research", displayName: "Sonar Deep Research",
               capabilities: [.streaming, .toolCalling, .reasoning, .nativePDF],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "sonar-reasoning", displayName: "Sonar Reasoning",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .nativePDF],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: DeepInfra

    static let deepInfraRecords: [Record] = [
        // Seeded
        Record(id: "zai-org/GLM-5.2", displayName: "GLM-5.2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "zai-org/GLM-5.1", displayName: "GLM-5.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.6-35B-A3B", displayName: "Qwen3.6 35B A3B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning", displayName: "Nemotron 3 Nano Omni 30B A3B Reasoning",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .videoInput, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "zai-org/GLM-5", displayName: "GLM-5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.5-397B-A17B", displayName: "Qwen3.5 397B A17B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.5-122B-A10B", displayName: "Qwen3.5 122B A10B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.5-35B-A3B", displayName: "Qwen3.5 35B A3B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.5-27B", displayName: "Qwen3.5 27B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.5-9B", displayName: "Qwen3.5 9B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "moonshotai/Kimi-K2-Instruct-0905", displayName: "Kimi K2 Instruct 0905",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "deepseek-ai/DeepSeek-V3.2", displayName: "DeepSeek V3.2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 163_840,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "deepseek-ai/DeepSeek-V4-Flash", displayName: "DeepSeek V4 Flash",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "deepseek-ai/DeepSeek-V4-Pro", displayName: "DeepSeek V4 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMaxAI/MiniMax-M2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_608,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-oss-120b", displayName: "GPT-OSS 120B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-org/GLM-4.7", displayName: "GLM-4.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "moonshotai/Kimi-K2.5", displayName: "Kimi K2.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-org/GLM-4.7-Flash", displayName: "GLM-4.7 Flash",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 202_752,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "nvidia/Nemotron-3-Nano-30B-A3B", displayName: "Nemotron 3 Nano 30B A3B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-oss-20b", displayName: "GPT-OSS 20B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B", displayName: "NVIDIA Nemotron 3 Super 120B A12B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "stepfun-ai/Step-3.5-Flash", displayName: "Step 3.5 Flash",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "Qwen/Qwen3-Max", displayName: "Qwen3 Max",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 256_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "Qwen/Qwen3-Max-Thinking", displayName: "Qwen3 Max Thinking",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 256_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: Together AI

    static let togetherRecords: [Record] = [
        // Seeded
        Record(id: "moonshotai/Kimi-K2.5", displayName: "Kimi K2.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "zai-org/GLM-5.2", displayName: "GLM-5.2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "zai-org/GLM-5", displayName: "GLM-5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "deepseek-ai/DeepSeek-V3.1", displayName: "DeepSeek V3.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "deepseek-ai/DeepSeek-V4-Pro", displayName: "DeepSeek V4 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 524_288,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "openai/gpt-oss-120b", displayName: "GPT-OSS 120B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.5-397B-A17B", displayName: "Qwen3.5 397B A17B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3-235B-A22B-Instruct-2507-tput", displayName: "Qwen3 235B A22B Instruct 2507",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3-Coder-Next-FP8", displayName: "Qwen3 Coder Next",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "MiniMaxAI/MiniMax-M2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 228_700,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8", displayName: "Qwen3 Coder 480B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 256_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "Qwen/Qwen3.5-9B", displayName: "Qwen3.5 9B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-org/GLM-4.7", displayName: "GLM-4.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-org/GLM-4.5-Air-FP8", displayName: "GLM 4.5 Air",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-oss-20b", displayName: "GPT-OSS 20B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "Qwen/Qwen3-Next-80B-A3B-Instruct", displayName: "Qwen3 Next 80B A3B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", displayName: "Llama 4 Maverick",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 1_048_576,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: xAI

    // Verified against docs.x.ai/developers/models + pricing (2026-07-12):
    // Chat/Code contexts are 500k (4.5), 1M (4.3 / 4.20 / multi-agent), 256k (build).
    // Multi-agent: built-in tools only (no client function tools), effort = agent count.
    // grok-4.5 reasoning always-on low/medium/high (default high); code_interpreter is
    // documented in tools overview examples. presence/frequency/stop rejected on reasoning.
    // Imagine: pro is an alias of quality; video-1.5 is image→video only (1080p supported).
    // Retired 4.1/* slugs still resolve (redirect to 4.3) but are catalog-only, not seeded.
    static let xAIRecords: [Record] = [
        // Seeded
        Record(id: "grok-4.5", displayName: "Grok 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 500_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-4.3", displayName: "Grok 4.3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_000_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-4.20", displayName: "Grok 4.20",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-4.20-0309-non-reasoning", displayName: "Grok 4.20 (Non-Reasoning)",
               capabilities: [.streaming, .toolCalling, .vision, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-4.20-multi-agent", displayName: "Grok 4.20 Multi-Agent",
               capabilities: [.streaming, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_000_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: true),
        // Reasoning is always-on and non-configurable for Build (no effort control).
        Record(id: "grok-build-0.1", displayName: "Grok Build 0.1",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 256_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-imagine-image", displayName: "Grok Imagine Image",
               capabilities: [.imageGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-imagine-image-quality", displayName: "Grok Imagine Image Quality",
               capabilities: [.imageGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-imagine-video", displayName: "Grok Imagine Video",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-imagine-video-1.5", displayName: "Grok Imagine Video 1.5",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only (aliases / snapshots / retired discovery IDs)
        Record(id: "grok-4.20-multi-agent-0309", displayName: "Grok 4.20 Multi-Agent 0309",
               capabilities: [.streaming, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_000_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-4.20-0309-reasoning", displayName: "Grok 4.20 0309 (Reasoning)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-imagine-image-pro", displayName: "Grok Imagine Image Pro",
               capabilities: [.imageGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-2-image-1212", displayName: "Grok 2 Image",
               capabilities: [.imageGeneration],
               contextWindow: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-imagine-video-1.5-preview", displayName: "Grok Imagine Video 1.5 (Preview)",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-imagine-video-1.5-2026-05-30", displayName: "Grok Imagine Video 1.5 (2026-05-30)",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        // Retired 2026-05-15 (still resolve via redirect to grok-4.3 / quality / build).
        Record(id: "grok-4-1-fast", displayName: "Grok 4.1 Fast",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-4-1", displayName: "Grok 4.1",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-4-1-fast-non-reasoning", displayName: "Grok 4.1 Fast (Non-Reasoning)",
               capabilities: [.streaming, .toolCalling, .vision, .promptCaching, .nativePDF],
               contextWindow: 1_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-4-1-fast-reasoning", displayName: "Grok 4.1 Fast (Reasoning)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: DeepSeek

    static let deepSeekRecords: [Record] = [
        Record(id: "deepseek-chat", displayName: "DeepSeek Chat",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "deepseek-reasoner", displayName: "DeepSeek Reasoner",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "deepseek-v3.2-exp", displayName: "DeepSeek V3.2 Exp",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "deepseek-v4-flash", displayName: "DeepSeek V4 Flash",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_000_000,
               maxOutputTokens: 384_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "deepseek-v4-pro", displayName: "DeepSeek V4 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_000_000,
               maxOutputTokens: 384_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
    ]

    // MARK: Zhipu Coding Plan

    static let zhipuCodingPlanRecords: [Record] = [
        // Z.ai exposes GLM-5.2 via a two-ID scheme: plain `glm-5.2` runs the standard
        // 200K window, and `glm-5.2[1m]` opts into the full 1,000,000-token context.
        // Both take `reasoning_effort` (high/max). https://docs.z.ai/devpack/latest-model
        Record(id: "glm-5.2[1m]", displayName: "GLM-5.2 (1M)",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_000_000,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "glm-5.2", displayName: "GLM-5.2",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 200_000,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "glm-5", displayName: "GLM-5",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 200_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "glm-4.7", displayName: "GLM-4.7",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 200_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
    ]

    // MARK: MiniMax

    static let minimaxRecords: [Record] = [
        Record(id: "MiniMax-M3", displayName: "MiniMax M3",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 512_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "MiniMax-M2.7", displayName: "MiniMax M2.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "MiniMax-M2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "MiniMax-M2.7-highspeed", displayName: "MiniMax M2.7 Highspeed",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2.5-highspeed", displayName: "MiniMax M2.5 Highspeed",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2.1", displayName: "MiniMax M2.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2.1-highspeed", displayName: "MiniMax M2.1 Highspeed",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2", displayName: "MiniMax M2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: MiniMax Coding Plan

    // The Token Plan uses MiniMax's unified OpenAI-compatible /v1 endpoint, where reasoning
    // is an enum toggle (thinking.type = disabled|adaptive), not an Anthropic thinking budget.
    static let minimaxCodingPlanRecords: [Record] = [
        Record(id: "MiniMax-M3", displayName: "MiniMax M3",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 512_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "MiniMax-M2.7", displayName: "MiniMax M2.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "MiniMax-M2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "MiniMax-M2.7-highspeed", displayName: "MiniMax M2.7 Highspeed",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2.5-highspeed", displayName: "MiniMax M2.5 Highspeed",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2.1", displayName: "MiniMax M2.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2.1-highspeed", displayName: "MiniMax M2.1 Highspeed",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2", displayName: "MiniMax M2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: Fireworks

    static let fireworksRecords: [Record] = [
        // Seeded
        Record(id: "fireworks/kimi-k2p6", displayName: "Kimi K2.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_100,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "fireworks/qwen3p6-plus", displayName: "Qwen3.6 Plus",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: true),
        Record(id: "accounts/fireworks/models/deepseek-v4-pro", displayName: "DeepSeek V4 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_600,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "fireworks/deepseek-v3p2", displayName: "DeepSeek V3.2",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 163_800,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "fireworks/kimi-k2-instruct-0905", displayName: "Kimi K2 Instruct 0905",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_100,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "fireworks/glm-5", displayName: "GLM-5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "fireworks/minimax-m2p5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_600,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "fireworks/minimax-m2p7", displayName: "MiniMax M2.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "fireworks/glm-5p2", displayName: "GLM-5.2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_040_384,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "fireworks/glm-5p1", displayName: "GLM-5.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "fireworks/kimi-k2p5", displayName: "Kimi K2.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_100,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "fireworks/qwen3-235b-a22b", displayName: "Qwen3 235B A22B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 131_100,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "fireworks/glm-4p7", displayName: "GLM-4.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "deepseek-ai/deepseek-v4-pro", displayName: "DeepSeek V4 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_600,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "fireworks/kimi-k2-thinking", displayName: "Kimi K2 Thinking",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262_100,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "accounts/fireworks/models/kimi-k2-thinking", displayName: "Kimi K2 Thinking",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262_100,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        // Alternate "accounts/fireworks/models/" IDs (same capabilities, not seeded separately)
        Record(id: "accounts/fireworks/models/qwen3p6-plus", displayName: "Qwen3.6 Plus",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "accounts/fireworks/models/deepseek-v3p2", displayName: "DeepSeek V3.2",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 163_800,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/kimi-k2-instruct-0905", displayName: "Kimi K2 Instruct 0905",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_100,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/glm-5", displayName: "GLM-5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/minimax-m2p5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_600,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/kimi-k2p6", displayName: "Kimi K2.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_100,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/kimi-k2p5", displayName: "Kimi K2.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_100,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/qwen3-235b-a22b", displayName: "Qwen3 235B A22B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 131_100,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/glm-4p7", displayName: "GLM-4.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        // Additional models present in ModelSettingsResolver (not fully supported)
        Record(id: "fireworks/minimax-m2p1", displayName: "MiniMax M2.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        Record(id: "accounts/fireworks/models/minimax-m2p1", displayName: "MiniMax M2.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        Record(id: "fireworks/minimax-m2", displayName: "MiniMax M2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_600,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        Record(id: "accounts/fireworks/models/minimax-m2", displayName: "MiniMax M2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_600,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        // Long-form alternate IDs for newly-added flagship serverless models
        Record(id: "accounts/fireworks/models/minimax-m2p7", displayName: "MiniMax M2.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/glm-5p2", displayName: "GLM-5.2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_040_384,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/glm-5p1", displayName: "GLM-5.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        // New serverless additions (Llama 3.3, Qwen3 8B)
        Record(id: "fireworks/llama-v3p3-70b-instruct", displayName: "Llama 3.3 70B Instruct",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/llama-v3p3-70b-instruct", displayName: "Llama 3.3 70B Instruct",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "fireworks/qwen3-8b", displayName: "Qwen3 8B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 40_960,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/qwen3-8b", displayName: "Qwen3 8B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 40_960,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: Groq

    static let groqRecords: [Record] = [
        // Seeded — appear in the model picker on first launch
        Record(id: "llama-3.3-70b-versatile", displayName: "Llama 3.3 70B Versatile",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 131_072,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "llama-3.1-8b-instant", displayName: "Llama 3.1 8B Instant",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 131_072,
               maxOutputTokens: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "openai/gpt-oss-120b", displayName: "GPT-OSS 120B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 131_072,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "openai/gpt-oss-20b", displayName: "GPT-OSS 20B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 131_072,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "groq/compound", displayName: "Groq Compound",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 131_072,
               maxOutputTokens: 8_192,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "groq/compound-mini", displayName: "Groq Compound Mini",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 131_072,
               maxOutputTokens: 8_192,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: Cerebras

    static let cerebrasRecords: [Record] = [
        // Retires from Cerebras 2026-05-27 — keep record for in-flight chats but drop "fully supported" badge.
        Record(id: "qwen-3-235b-a22b-instruct-2507", displayName: "Qwen 3 235B A22B Instruct 2507 (Deprecated)",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 65_000,
               maxOutputTokens: 32_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "zai-glm-4.7", displayName: "ZAI GLM-4.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 64_000,
               maxOutputTokens: 40_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-oss-120b", displayName: "GPT-OSS 120B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
    ]

    // MARK: SambaNova

    static let sambaNovaRecords: [Record] = [
        // Seeded — appear in the model picker on first launch
        Record(id: "MiniMax-M2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 160_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Kept unseeded/unsupported by default due unstable behavior in real-world usage.
        Record(id: "DeepSeek-V3.2", displayName: "DeepSeek V3.2",
               capabilities: [.streaming],
               contextWindow: 8_192,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gpt-oss-120b", displayName: "GPT-OSS 120B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        // Catalog-only — recognized when fetched via the API
        Record(id: "DeepSeek-R1-0528", displayName: "DeepSeek R1 0528",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "DeepSeek-R1-Distill-Llama-70B", displayName: "DeepSeek R1 Distill Llama 70B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: false, isSeeded: false),
        Record(id: "DeepSeek-V3-0324", displayName: "DeepSeek V3 0324",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "DeepSeek-V3.1", displayName: "DeepSeek V3.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "DeepSeek-V3.1-Terminus", displayName: "DeepSeek V3.1 Terminus",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "Meta-Llama-3.3-70B-Instruct", displayName: "Llama 3.3 70B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "Meta-Llama-3.1-8B-Instruct", displayName: "Llama 3.1 8B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 16_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "Llama-4-Maverick-17B-128E-Instruct", displayName: "Llama 4 Maverick 17B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "Qwen3-235B-A22B-Instruct-2507", displayName: "Qwen3 235B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "Qwen3-32B", displayName: "Qwen3 32B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 32_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: MorphLLM

    // MARK: Xiaomi MiMo Token Plan

    static let mimoTokenPlanOpenAIRecords: [Record] = [
        Record(id: MiMoModelIDs.v25Pro, displayName: "MiMo V2.5 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: MiMoModelIDs.v25, displayName: "MiMo V2.5",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .videoInput, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: MiMoModelIDs.v2Pro, displayName: "MiMo V2 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: MiMoModelIDs.v2Omni, displayName: "MiMo V2 Omni",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .videoInput, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: MiMoModelIDs.v2Flash, displayName: "MiMo V2 Flash",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
    ]

    static let mimoTokenPlanAnthropicRecords: [Record] = [
        Record(id: MiMoModelIDs.v25Pro, displayName: "MiMo V2.5 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: MiMoModelIDs.v25, displayName: "MiMo V2.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: MiMoModelIDs.v2Pro, displayName: "MiMo V2 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: MiMoModelIDs.v2Omni, displayName: "MiMo V2 Omni",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: MiMoModelIDs.v2Flash, displayName: "MiMo V2 Flash",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
    ]

    // MARK: Kimi for Coding

    // Model IDs and context windows verified against the official Kimi Code docs
    // (kimi.com/code/docs): the Anthropic-compatible endpoint is
    // `https://api.kimi.com/coding/v1/messages`; K2.7 Code requires Thinking mode
    // (requests without it are routed to K2.6), and K3 runs deep thinking by
    // default — so both expose a thinking toggle. `k3[1m]` is the documented
    // 1M-context K3 variant. K2.7 Code vision + 262,144 max output match the
    // repo's existing `kimi-k2.7-code` record (models.dev). K3 vision and max
    // output are undocumented, so they stay conservative.
    static let kimiForCodingRecords: [Record] = [
        Record(id: "k3[1m]", displayName: "Kimi K3 (1M)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "k3", displayName: "Kimi K3",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "kimi-for-coding", displayName: "Kimi K2.7 Code",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "kimi-for-coding-highspeed", displayName: "Kimi K2.7 Code HighSpeed",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
    ]

    // MARK: OpenCode Go

    static let opencodeGoRecords: [Record] = [
        // GLM-5.2 leads OpenCode Go's GLM line (verified on models.dev `opencode-go` and
        // opencode.ai/docs/go): 1M context, 131K output, reasoning via OpenAI-style
        // reasoning_effort on the OpenAI-compatible /chat/completions endpoint. Seeded
        // first so it is OpenCode Go's first-launch default (preferredModelID = models.first).
        Record(id: "glm-5.2", displayName: "GLM-5.2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "glm-5", displayName: "GLM-5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "kimi-k2.5", displayName: "Kimi K2.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "kimi-k2.6", displayName: "Kimi K2.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        // Kimi K2.7 Code (live on the Go /models list since 2026-06-12; verified against
        // models.dev `opencode-go`): 262,144 context AND output, reasoning always-on with
        // NO effort control (empty reasoning_options — the gateway ignores reasoning_effort
        // for it), thinking interleaved via `reasoning_content`. reasoningConfig stays nil
        // so Jin never sends an effort it can't honor. models.dev also lists video input,
        // but this model routes through the OpenAI-compatible endpoint whose message
        // translation has no video part builder, so .videoInput is deliberately not claimed.
        Record(id: "kimi-k2.7-code", displayName: "Kimi K2.7 Code",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "mimo-v2.5-pro", displayName: "MiMo V2.5 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "mimo-v2.5", displayName: "MiMo V2.5",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "deepseek-v4-pro", displayName: "DeepSeek V4 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_000_000,
               maxOutputTokens: 384_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "deepseek-v4-flash", displayName: "DeepSeek V4 Flash",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_000_000,
               maxOutputTokens: 384_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "minimax-m3", displayName: "MiniMax M3",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 512_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: true),
        Record(id: "minimax-m2.7", displayName: "MiniMax M2.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: true),
        Record(id: "minimax-m2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: true),
        Record(id: "glm-5.1", displayName: "GLM-5.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        // Qwen + MiniMax are served via OpenCode Go's Anthropic /messages endpoint, where
        // reasoning is an Anthropic thinking budget (matches the minimax-* rows below).
        Record(id: "qwen3.7-max", displayName: "Qwen3.7 Max",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: true),
        // Qwen3.7 Plus (live on the Go /models list since 2026-06-02; verified against
        // models.dev `opencode-go`): 1M context / 65,536 output, served via the Anthropic
        // /messages endpoint (@ai-sdk/anthropic) with a thinking budget like the other
        // qwen3.7 models — it must also be routed in
        // OpenCodeGoAdapter.anthropicMessagesModelIDs. models.dev also lists video input,
        // but the Anthropic /messages translation has no video part builder (it replaces
        // .video parts with a placeholder notice), so .videoInput is deliberately not
        // claimed — same rationale as kimi-k2.7-code above.
        Record(id: "qwen3.7-plus", displayName: "Qwen3.7 Plus",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: true),
        Record(id: "qwen3.6-plus", displayName: "Qwen3.6 Plus",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               maxOutputTokens: 65_536,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only — recognized when fetched via the API
        Record(id: "qwen3.5-plus", displayName: "Qwen3.5 Plus",
               capabilities: [.streaming, .toolCalling, .vision, .videoInput],
               contextWindow: 1_000_000,
               maxOutputTokens: 65_536,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        // MiMo V2 (pro/omni) are still served but deprecated on OpenCode Go (superseded by
        // the seeded V2.5 variants), so they are recognized-when-fetched rather than seeded.
        Record(id: "mimo-v2-pro", displayName: "MiMo V2 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "mimo-v2-omni", displayName: "MiMo V2 Omni",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "hy3-preview", displayName: "Hy3 Preview",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 256_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "big-pickle", displayName: "Big Pickle",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "deepseek-v4-flash-free", displayName: "DeepSeek V4 Flash (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 256_000,
               maxOutputTokens: 256_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax-m2.5-free", displayName: "MiniMax M2.5 (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: false),
        Record(id: "ring-2.6-1t-free", displayName: "Ring 2.6 1T (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "trinity-large-preview-free", displayName: "Trinity Large Thinking (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 80_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "nemotron-3-super-free", displayName: "Nemotron 3 Super (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: Meta

    // Muse Spark 1.1 — Meta's first paid API model (Meta Model API public preview,
    // launched 2026-07-09; verified against dev.meta.ai docs): 1,048,576 context /
    // 131,072 output ("Limits: context 1048576, output 131072" in Meta's overview),
    // text+image(+video/PDF) input, text output. Reasoning is always-on — sending
    // reasoning_effort "none" returns HTTP 400 — with minimal..xhigh efforts and a
    // model-determined default when omitted. Caching is implicit server-side with an
    // optional prompt_cache_key hint. .videoInput/.nativePDF are deliberately not
    // claimed: the Chat Completions wire format Jin uses has no verified video/PDF
    // part encoding, so those attachments go through Jin's extraction paths instead.
    static let metaRecords: [Record] = [
        Record(id: "muse-spark-1.1", displayName: "Muse Spark 1.1",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
    ]

    // MARK: MorphLLM

    static let morphLLMRecords: [Record] = [
        // Seeded — appear in the model picker on first launch
        Record(id: "auto", displayName: "Morph Auto",
               capabilities: [.streaming],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "morph-v3-large", displayName: "Morph v3 Large",
               capabilities: [.streaming],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "morph-v3-fast", displayName: "Morph v3 Fast",
               capabilities: [.streaming],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
    ]
}
