import Foundation

// MARK: - Independent Provider Records

extension ModelCatalog {

    // MARK: Anthropic

    static let anthropicRecords: [Record] = [
        Record(id: "claude-opus-4-7", displayName: "Claude Opus 4.7",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-opus-4-6", displayName: "Claude Opus 4.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-sonnet-4-6", displayName: "Claude Sonnet 4.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-opus-4-5-20251101", displayName: "Claude Opus 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-sonnet-4-5-20250929", displayName: "Claude Sonnet 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-haiku-4-5-20251001", displayName: "Claude Haiku 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-opus-4", displayName: "Claude Opus 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "claude-sonnet-4", displayName: "Claude Sonnet 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "claude-haiku-4", displayName: "Claude Haiku 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 200_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: Perplexity

    static let perplexityRecords: [Record] = [
        // Seeded (capabilities match DefaultProviderSeeds; nativePDF added per JinModelSupport)
        Record(id: "sonar", displayName: "Sonar",
               capabilities: [.streaming, .vision, .nativePDF],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: true),
        Record(id: "sonar-pro", displayName: "Sonar Pro",
               capabilities: [.streaming, .toolCalling, .vision, .nativePDF],
               contextWindow: 200_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "sonar-reasoning-pro", displayName: "Sonar Reasoning Pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .nativePDF],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "sonar-deep-research", displayName: "Sonar Deep Research",
               capabilities: [.streaming, .toolCalling, .reasoning, .nativePDF],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "sonar-reasoning", displayName: "Sonar Reasoning",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .nativePDF],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: DeepInfra

    static let deepInfraRecords: [Record] = [
        // Seeded
        Record(id: "zai-org/GLM-5", displayName: "GLM-5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.5-397B-A17B", displayName: "Qwen3.5 397B A17B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.5-122B-A10B", displayName: "Qwen3.5 122B A10B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.5-35B-A3B", displayName: "Qwen3.5 35B A3B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.5-27B", displayName: "Qwen3.5 27B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.5-9B", displayName: "Qwen3.5 9B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "moonshotai/Kimi-K2-Instruct-0905", displayName: "Kimi K2 Instruct 0905",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "deepseek-ai/DeepSeek-V3.2", displayName: "DeepSeek V3.2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 163_840,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMaxAI/MiniMax-M2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_608,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-oss-120b", displayName: "GPT-OSS 120B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-org/GLM-4.7", displayName: "GLM-4.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "moonshotai/Kimi-K2.5", displayName: "Kimi K2.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-org/GLM-4.7-Flash", displayName: "GLM-4.7 Flash",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 202_752,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "nvidia/Nemotron-3-Nano-30B-A3B", displayName: "Nemotron 3 Nano 30B A3B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-oss-20b", displayName: "GPT-OSS 20B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: Together AI

    static let togetherRecords: [Record] = [
        // Seeded
        Record(id: "moonshotai/Kimi-K2.5", displayName: "Kimi K2.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "zai-org/GLM-5", displayName: "GLM-5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "deepseek-ai/DeepSeek-V3.1", displayName: "DeepSeek V3.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "openai/gpt-oss-120b", displayName: "GPT-OSS 120B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3.5-397B-A17B", displayName: "Qwen3.5 397B A17B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3-235B-A22B-Instruct-2507-tput", displayName: "Qwen3 235B A22B Instruct 2507",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "Qwen/Qwen3-Coder-Next-FP8", displayName: "Qwen3 Coder Next",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "MiniMaxAI/MiniMax-M2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 228_700,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8", displayName: "Qwen3 Coder 480B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 256_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "Qwen/Qwen3.5-9B", displayName: "Qwen3.5 9B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-org/GLM-4.7", displayName: "GLM-4.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-org/GLM-4.5-Air-FP8", displayName: "GLM 4.5 Air",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-oss-20b", displayName: "GPT-OSS 20B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "Qwen/Qwen3-Next-80B-A3B-Instruct", displayName: "Qwen3 Next 80B A3B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", displayName: "Llama 4 Maverick",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 1_048_576,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: xAI

    static let xAIRecords: [Record] = [
        // Seeded
        Record(id: "grok-4-1-fast", displayName: "Grok 4.1 Fast",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 2_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-4-1", displayName: "Grok 4.1",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 2_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-imagine-image", displayName: "Grok Imagine Image",
               capabilities: [.imageGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-imagine-image-pro", displayName: "Grok Imagine Image Pro",
               capabilities: [.imageGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-2-image-1212", displayName: "Grok 2 Image",
               capabilities: [.imageGeneration],
               contextWindow: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-imagine-video", displayName: "Grok Imagine Video",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "grok-4-1-fast-non-reasoning", displayName: "Grok 4.1 Fast (Non-Reasoning)",
               capabilities: [.streaming, .toolCalling, .vision, .promptCaching, .nativePDF],
               contextWindow: 2_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-4-1-fast-reasoning", displayName: "Grok 4.1 Fast (Reasoning)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 2_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: DeepSeek

    static let deepSeekRecords: [Record] = [
        Record(id: "deepseek-chat", displayName: "DeepSeek Chat",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "deepseek-reasoner", displayName: "DeepSeek Reasoner",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "deepseek-v3.2-exp", displayName: "DeepSeek V3.2 Exp",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
    ]

    // MARK: Zhipu Coding Plan

    static let zhipuCodingPlanRecords: [Record] = [
        Record(id: "glm-5", displayName: "GLM-5",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 200_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "glm-4.7", displayName: "GLM-4.7",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 200_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
    ]

    // MARK: MiniMax

    static let minimaxRecords: [Record] = [
        Record(id: "MiniMax-M2.7", displayName: "MiniMax M2.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "MiniMax-M2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: true),
        Record(id: "MiniMax-M2.7-highspeed", displayName: "MiniMax M2.7 Highspeed",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2.5-highspeed", displayName: "MiniMax M2.5 Highspeed",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2.1", displayName: "MiniMax M2.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2.1-highspeed", displayName: "MiniMax M2.1 Highspeed",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2", displayName: "MiniMax M2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: MiniMax Coding Plan

    static let minimaxCodingPlanRecords: [Record] = [
        Record(id: "MiniMax-M2.7", displayName: "MiniMax M2.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: true),
        Record(id: "MiniMax-M2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: true),
        Record(id: "MiniMax-M2.7-highspeed", displayName: "MiniMax M2.7 Highspeed",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2.5-highspeed", displayName: "MiniMax M2.5 Highspeed",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2.1", displayName: "MiniMax M2.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2.1-highspeed", displayName: "MiniMax M2.1 Highspeed",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: false),
        Record(id: "MiniMax-M2", displayName: "MiniMax M2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: Fireworks

    static let fireworksRecords: [Record] = [
        // Seeded (canonical "fireworks/" prefix IDs)
        Record(id: "fireworks/qwen3p6-plus", displayName: "Qwen3.6 Plus",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: true),
        Record(id: "fireworks/deepseek-v3p2", displayName: "DeepSeek V3.2",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 163_800,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "fireworks/kimi-k2-instruct-0905", displayName: "Kimi K2 Instruct 0905",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_100,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "fireworks/glm-5", displayName: "GLM-5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "fireworks/minimax-m2p5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_600,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "fireworks/kimi-k2p5", displayName: "Kimi K2.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_100,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "fireworks/qwen3-235b-a22b", displayName: "Qwen3 235B A22B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 131_100,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "fireworks/glm-4p7", displayName: "GLM-4.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        // Alternate "accounts/fireworks/models/" IDs (same capabilities, not seeded separately)
        Record(id: "accounts/fireworks/models/qwen3p6-plus", displayName: "Qwen3.6 Plus",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "accounts/fireworks/models/deepseek-v3p2", displayName: "DeepSeek V3.2",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 163_800,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/kimi-k2-instruct-0905", displayName: "Kimi K2 Instruct 0905",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_100,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/glm-5", displayName: "GLM-5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/minimax-m2p5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_600,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/kimi-k2p5", displayName: "Kimi K2.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_100,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/qwen3-235b-a22b", displayName: "Qwen3 235B A22B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 131_100,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/glm-4p7", displayName: "GLM-4.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        // Additional models present in ModelSettingsResolver (not fully supported)
        Record(id: "fireworks/minimax-m2p1", displayName: "MiniMax M2.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        Record(id: "accounts/fireworks/models/minimax-m2p1", displayName: "MiniMax M2.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        Record(id: "fireworks/minimax-m2", displayName: "MiniMax M2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_600,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        Record(id: "accounts/fireworks/models/minimax-m2", displayName: "MiniMax M2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_600,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
    ]

    // MARK: Cerebras

    static let cerebrasRecords: [Record] = [
        Record(id: "qwen-3-235b-a22b-instruct-2507", displayName: "Qwen 3 235B A22B Instruct 2507",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 65_000,
               maxOutputTokens: 32_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-glm-4.7", displayName: "ZAI GLM-4.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 64_000,
               maxOutputTokens: 40_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-oss-120b", displayName: "GPT-OSS 120B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
    ]

    // MARK: SambaNova

    static let sambaNovaRecords: [Record] = [
        // Seeded — appear in the model picker on first launch
        Record(id: "MiniMax-M2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 160_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Kept unseeded/unsupported by default due unstable behavior in real-world usage.
        Record(id: "DeepSeek-V3.2", displayName: "DeepSeek V3.2",
               capabilities: [.streaming],
               contextWindow: 8_192,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gpt-oss-120b", displayName: "GPT-OSS 120B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        // Catalog-only — recognized when fetched via the API
        Record(id: "DeepSeek-R1-0528", displayName: "DeepSeek R1 0528",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "DeepSeek-R1-Distill-Llama-70B", displayName: "DeepSeek R1 Distill Llama 70B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: false, isSeeded: false),
        Record(id: "DeepSeek-V3-0324", displayName: "DeepSeek V3 0324",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "DeepSeek-V3.1", displayName: "DeepSeek V3.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "DeepSeek-V3.1-Terminus", displayName: "DeepSeek V3.1 Terminus",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "Meta-Llama-3.3-70B-Instruct", displayName: "Llama 3.3 70B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "Meta-Llama-3.1-8B-Instruct", displayName: "Llama 3.1 8B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 16_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "Llama-4-Maverick-17B-128E-Instruct", displayName: "Llama 4 Maverick 17B",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "Qwen3-235B-A22B-Instruct-2507", displayName: "Qwen3 235B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "Qwen3-32B", displayName: "Qwen3 32B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 32_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: MorphLLM

    // MARK: OpenCode Go

    static let opencodeGoRecords: [Record] = [
        Record(id: "glm-5", displayName: "GLM-5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_752,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "kimi-k2.5", displayName: "Kimi K2.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "minimax-m2.7", displayName: "MiniMax M2.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: true),
        Record(id: "minimax-m2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 204_800,
               maxOutputTokens: 204_800,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 10_000),
               isFullySupported: true, isSeeded: true),
    ]

    // MARK: MorphLLM

    static let morphLLMRecords: [Record] = [
        // Seeded — appear in the model picker on first launch
        Record(id: "auto", displayName: "Morph Auto",
               capabilities: [.streaming],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "morph-v3-large", displayName: "Morph v3 Large",
               capabilities: [.streaming],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "morph-v3-fast", displayName: "Morph v3 Fast",
               capabilities: [.streaming],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
    ]
}
