import Foundation

// MARK: - Gemini, Vertex AI & OpenRouter Records

extension ModelCatalog {

    // MARK: Gemini (AI Studio)

    static let geminiRecords: [Record] = [
        // Seeded
        Record(id: "gemini-3-pro-preview", displayName: "Gemini 3 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3-pro-image-preview", displayName: "Gemini 3 Pro Image (Preview)",
               capabilities: [.streaming, .vision, .reasoning, .imageGeneration],
               contextWindow: 65_536,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-image-preview", displayName: "Gemini 3.1 Flash Image (Preview)",
               capabilities: [.streaming, .vision, .reasoning, .nativePDF, .imageGeneration],
               contextWindow: 131_072,
               maxOutputTokens: 32_768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3-flash-preview", displayName: "Gemini 3 Flash (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-lite-preview", displayName: "Gemini 3.1 Flash-Lite (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-2.5-flash-image", displayName: "Gemini 2.5 Flash Image",
               capabilities: [.streaming, .vision, .imageGeneration],
               contextWindow: 65_536,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "gemini-3", displayName: "Gemini 3",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-3-pro", displayName: "Gemini 3 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemma-4-31b-it", displayName: "Gemma 4 31B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-2", displayName: "Veo 2",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-3", displayName: "Veo 3",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: Vertex AI

    static let vertexAIRecords: [Record] = [
        // Seeded
        Record(id: "gemini-3-pro-preview", displayName: "Gemini 3 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3-pro-image-preview", displayName: "Gemini 3 Pro Image (Preview)",
               capabilities: [.streaming, .vision, .reasoning, .imageGeneration],
               contextWindow: 65_536,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-image-preview", displayName: "Gemini 3.1 Flash Image (Preview)",
               capabilities: [.streaming, .vision, .reasoning, .nativePDF, .imageGeneration],
               contextWindow: 131_072,
               maxOutputTokens: 32_768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3-flash-preview", displayName: "Gemini 3 Flash (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-lite-preview", displayName: "Gemini 3.1 Flash-Lite (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-2.5-pro", displayName: "Gemini 2.5 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-2.5-flash-image", displayName: "Gemini 2.5 Flash Image",
               capabilities: [.streaming, .vision, .imageGeneration],
               contextWindow: 32_768,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "gemini-3", displayName: "Gemini 3",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-3-pro", displayName: "Gemini 3 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-2.5", displayName: "Gemini 2.5",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-2.5-flash-lite", displayName: "Gemini 2.5 Flash Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: false, isSeeded: false),
        Record(id: "veo-2", displayName: "Veo 2",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-3", displayName: "Veo 3",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: OpenRouter

    static let openRouterRecords: [Record] = [
        Record(id: "xiaomi/mimo-v2-omni", displayName: "MiMo V2 Omni",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 262_144,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "xiaomi/mimo-v2-pro", displayName: "MiMo V2 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "xiaomi/mimo-v2-flash", displayName: "MiMo V2 Flash",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 262_144,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2.7", displayName: "MiniMax M2.7",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_608,
               maxOutputTokens: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2.5:free", displayName: "MiniMax M2.5 (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_608,
               maxOutputTokens: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2-her", displayName: "MiniMax M2-her",
               capabilities: [.streaming, .promptCaching],
               contextWindow: 65_536,
               maxOutputTokens: 2_048,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2.1", displayName: "MiniMax M2.1",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2", displayName: "MiniMax M2",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 196_608,
               maxOutputTokens: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m1", displayName: "MiniMax M1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 40_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-01", displayName: "MiniMax-01",
               capabilities: [.streaming, .vision],
               contextWindow: 1_000_192,
               maxOutputTokens: 1_000_192,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3-pro-preview", displayName: "Gemini 3 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemma-4-31b-it", displayName: "Gemma 4 31B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemma-4-26b-a4b-it", displayName: "Gemma 4 26B A4B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
    ]
}
