import Foundation

// MARK: - OpenAI, Codex App Server, Cloudflare AI Gateway & Vercel AI Gateway Records

extension ModelCatalog {

    // MARK: OpenAI (also used for openaiWebSocket via the entry/seededModels redirects)

    static let openAIRecords: [Record] = [
        // Seeded — appear in the model picker on first launch
        Record(id: "gpt-5.4", displayName: "GPT-5.4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_050_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.4-2026-03-05", displayName: "GPT-5.4 (2026-03-05)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_050_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.4-pro", displayName: "GPT-5.4 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_050_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.4-pro-2026-03-05", displayName: "GPT-5.4 Pro (2026-03-05)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_050_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.2", displayName: "GPT-5.2",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.2-2025-12-11", displayName: "GPT-5.2 (2025-12-11)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.4-mini", displayName: "GPT-5.4 Mini",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.4-mini-2026-03-17", displayName: "GPT-5.4 Mini (2026-03-17)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.4-nano", displayName: "GPT-5.4 Nano",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.4-nano-2026-03-17", displayName: "GPT-5.4 Nano (2026-03-17)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.3-codex", displayName: "GPT-5.3 Codex",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 400_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.3-chat-latest", displayName: "GPT-5.3 Chat (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .promptCaching],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-4o", displayName: "GPT-4o",
               capabilities: [.streaming, .toolCalling, .vision, .promptCaching, .nativePDF],
               contextWindow: 128_000,
               maxOutputTokens: 16_384,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only — recognized when fetched via the API
        // Note: gpt-5 (unversioned) does not have nativePDF; use gpt-5.2+ for native PDF.
        Record(id: "gpt-5", displayName: "GPT-5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .codeExecution],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "o3", displayName: "o3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 200_000,
               maxOutputTokens: 100_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "o4", displayName: "o4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-4o-audio-preview", displayName: "GPT-4o Audio Preview",
               capabilities: [.streaming, .toolCalling, .audio],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gpt-4o-audio-preview-2024-10-01", displayName: "GPT-4o Audio Preview (2024-10-01)",
               capabilities: [.streaming, .toolCalling, .audio],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gpt-4o-mini-audio-preview", displayName: "GPT-4o Mini Audio Preview",
               capabilities: [.streaming, .toolCalling, .audio],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gpt-4o-mini-audio-preview-2024-12-17", displayName: "GPT-4o Mini Audio Preview (2024-12-17)",
               capabilities: [.streaming, .toolCalling, .audio],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gpt-4o-realtime-preview", displayName: "GPT-4o Realtime Preview",
               capabilities: [.streaming, .toolCalling, .audio],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gpt-4o-realtime-preview-2024-10-01", displayName: "GPT-4o Realtime Preview (2024-10-01)",
               capabilities: [.streaming, .toolCalling, .audio],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gpt-4o-realtime-preview-2024-12-17", displayName: "GPT-4o Realtime Preview (2024-12-17)",
               capabilities: [.streaming, .toolCalling, .audio],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gpt-4o-mini-realtime-preview", displayName: "GPT-4o Mini Realtime Preview",
               capabilities: [.streaming, .toolCalling, .audio],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gpt-4o-mini-realtime-preview-2024-12-17", displayName: "GPT-4o Mini Realtime Preview (2024-12-17)",
               capabilities: [.streaming, .toolCalling, .audio],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gpt-realtime", displayName: "GPT Realtime",
               capabilities: [.streaming, .toolCalling, .audio],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gpt-realtime-mini", displayName: "GPT Realtime Mini",
               capabilities: [.streaming, .toolCalling, .audio],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        // Image generation models
        Record(id: "gpt-image-1.5", displayName: "GPT Image 1.5",
               capabilities: [.imageGeneration],
               contextWindow: 32_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-image-1", displayName: "GPT Image 1",
               capabilities: [.imageGeneration],
               contextWindow: 32_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-image-1-mini", displayName: "GPT Image 1 Mini",
               capabilities: [.imageGeneration],
               contextWindow: 32_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "dall-e-3", displayName: "DALL-E 3",
               capabilities: [.imageGeneration],
               contextWindow: 4_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "dall-e-2", displayName: "DALL-E 2",
               capabilities: [.imageGeneration],
               contextWindow: 1_000,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
    ]

    // MARK: Codex App Server

    static let codexAppServerRecords: [Record] = [
        Record(id: "gpt-5.1-codex", displayName: "GPT-5.1 Codex",
               capabilities: [.streaming, .reasoning],
               contextWindow: 256_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: true),
    ]

    // MARK: Cloudflare AI Gateway

    static let cloudflareAIGatewayRecords: [Record] = [
        // OpenAI
        Record(id: "openai/gpt-5", displayName: "GPT-5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.2", displayName: "GPT-5.2",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.2-2025-12-11", displayName: "GPT-5.2 (2025-12-11)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.3-codex", displayName: "GPT-5.3 Codex",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.4-mini", displayName: "GPT-5.4 Mini",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.4-nano", displayName: "GPT-5.4 Nano",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.3-chat-latest", displayName: "GPT-5.3 Chat (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .promptCaching],
               contextWindow: 128_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-4o", displayName: "GPT-4o",
               capabilities: [.streaming, .toolCalling, .vision, .promptCaching],
               contextWindow: 128_000,
               maxOutputTokens: 16_384,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/o3", displayName: "o3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 200_000,
               maxOutputTokens: 100_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/o4", displayName: "o4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),

        // Anthropic
        Record(id: "anthropic/claude-opus-4-6", displayName: "Claude Opus 4.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 200_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-sonnet-4-6", displayName: "Claude Sonnet 4.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4-5-20251101", displayName: "Claude Opus 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-sonnet-4-5-20250929", displayName: "Claude Sonnet 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-haiku-4-5-20251001", displayName: "Claude Haiku 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4", displayName: "Claude Opus 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 200_000,
               maxOutputTokens: 32_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-sonnet-4", displayName: "Claude Sonnet 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-haiku-4", displayName: "Claude Haiku 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 200_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: false),

        // Vertex via Cloudflare compound path
        Record(id: "google-vertex-ai/google/gemini-3", displayName: "Gemini 3",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "google-vertex-ai/google/gemini-3-pro", displayName: "Gemini 3 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        Record(id: "google-vertex-ai/google/gemini-3-pro-preview", displayName: "Gemini 3 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "google-vertex-ai/google/gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "google-vertex-ai/google/gemini-3-flash-preview", displayName: "Gemini 3 Flash (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "google-vertex-ai/google/gemini-2.5", displayName: "Gemini 2.5",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: false),
        Record(id: "google-vertex-ai/google/gemini-2.5-pro", displayName: "Gemini 2.5 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: false),
        Record(id: "google-vertex-ai/google/gemini-2.5-flash", displayName: "Gemini 2.5 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: false, isSeeded: false),
        Record(id: "google-vertex-ai/google/gemini-2.5-flash-lite", displayName: "Gemini 2.5 Flash Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: false, isSeeded: false),

        // AI Studio via Cloudflare compound path
        Record(id: "google-ai-studio/gemini-3", displayName: "Gemini 3",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google-ai-studio/gemini-3-pro", displayName: "Gemini 3 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: false, isSeeded: false),
        Record(id: "google-ai-studio/gemini-3-pro-preview", displayName: "Gemini 3 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google-ai-studio/gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google-ai-studio/gemini-3-flash-preview", displayName: "Gemini 3 Flash (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
    ]

    // MARK: Vercel AI Gateway

    static let vercelAIGatewayRecords: [Record] = [
        // OpenAI
        Record(id: "openai/gpt-5", displayName: "GPT-5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.2", displayName: "GPT-5.2",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.3-codex", displayName: "GPT-5.3 Codex",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.4-mini", displayName: "GPT-5.4 Mini",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.4-nano", displayName: "GPT-5.4 Nano",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-4o", displayName: "GPT-4o",
               capabilities: [.streaming, .toolCalling, .vision, .promptCaching],
               contextWindow: 128_000,
               maxOutputTokens: 16_384,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/o3", displayName: "o3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 200_000,
               maxOutputTokens: 100_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-oss-120b", displayName: "GPT-OSS 120B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),

        // Anthropic
        Record(id: "anthropic/claude-opus-4.6", displayName: "Claude Opus 4.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 200_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-sonnet-4.6", displayName: "Claude Sonnet 4.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4.5", displayName: "Claude Opus 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-sonnet-4.5", displayName: "Claude Sonnet 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-haiku-4.5", displayName: "Claude Haiku 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 1024),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4", displayName: "Claude Opus 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 200_000,
               maxOutputTokens: 32_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-sonnet-4", displayName: "Claude Sonnet 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),

        // Google Gemini
        Record(id: "google/gemini-3-pro-preview", displayName: "Gemini 3 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-2.5-pro", displayName: "Gemini 2.5 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.1-flash-image-preview", displayName: "Gemini 3.1 Flash Image (Preview)",
               capabilities: [.streaming, .vision, .reasoning, .imageGeneration],
               contextWindow: 131_072,
               maxOutputTokens: 32_768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-2.5-flash-image", displayName: "Gemini 2.5 Flash Image",
               capabilities: [.streaming, .vision, .imageGeneration],
               contextWindow: 32_768,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
    ]
}
