import Foundation

// MARK: - Gemini, Vertex AI & OpenRouter Records

extension ModelCatalog {

    // MARK: Shared Veo Video-Generation Records

    /// Veo model records shared between the Gemini (AI Studio) and Vertex AI catalogs.
    /// Veo 3.0 / 2.0 `*-001` IDs were shut down 2026-06-30 (docs deprecations page);
    /// keep catalog-only recognition for persisted conversations. Prefer 3.1 previews.
    private static let veoVideoRecords: [Record] = [
        Record(id: "veo-3.1-generate-preview", displayName: "Veo 3.1 (Preview)",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-3.1-fast-generate-preview", displayName: "Veo 3.1 Fast (Preview)",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-3.1-lite-generate-preview", displayName: "Veo 3.1 Lite (Preview)",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        // Catalog aliases / legacy discovery IDs
        Record(id: "veo-2", displayName: "Veo 2",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-3", displayName: "Veo 3",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        // Shut down 2026-06-30 — recognized for legacy data only
        Record(id: "veo-3.0-generate-001", displayName: "Veo 3 (Retired)",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "veo-3.0-fast-generate-001", displayName: "Veo 3 Fast (Retired)",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "veo-2.0-generate-001", displayName: "Veo 2 (Retired)",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
    ]


    // MARK: Gemini (AI Studio)

    // Seed list verified against ai.google.dev/gemini-api/docs/models + deprecations
    // (2026-07-15). Shut-down previews stay catalog-only for legacy persisted chats.
    static let geminiRecords: [Record] = [
        // Seeded — live stable / current preview IDs only
        Record(id: "gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3-pro-image", displayName: "Gemini 3 Pro Image",
               capabilities: [.streaming, .vision, .reasoning, .imageGeneration],
               contextWindow: 65_536,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-image", displayName: "Gemini 3.1 Flash Image",
               capabilities: [.streaming, .vision, .reasoning, .nativePDF, .imageGeneration],
               contextWindow: 131_072,
               maxOutputTokens: 32_768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        // Docs: 65_536 input / 4_096 output; thinking minimal|high; image size 1K only.
        Record(id: "gemini-3.1-flash-lite-image", displayName: "Gemini 3.1 Flash-Lite Image",
               capabilities: [.streaming, .vision, .reasoning, .imageGeneration],
               contextWindow: 65_536,
               maxOutputTokens: 4_096,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3-flash-preview", displayName: "Gemini 3 Flash (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        // GA 2026-08-13. Thinking is LOW/MEDIUM/HIGH — MINIMAL is rejected by the API.
        Record(id: "gemini-3.7-flash", displayName: "Gemini 3.7 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.6-flash", displayName: "Gemini 3.6 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.5-flash", displayName: "Gemini 3.5 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.5-flash-lite", displayName: "Gemini 3.5 Flash-Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-lite", displayName: "Gemini 3.1 Flash-Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-2.5-flash-image", displayName: "Gemini 2.5 Flash Image",
               capabilities: [.streaming, .vision, .imageGeneration],
               contextWindow: 65_536,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Gemini 2.5 text on AI Studio: vision yes, `.nativePDF` no. The Gemini
        // adapter's nativePDFModelIDs is Gemini 3-only, so offering Native here
        // would send a filename stub. Vertex keeps `.nativePDF` for the same IDs
        // because that adapter can inline application/pdf.
        Record(id: "gemini-2.5-pro", displayName: "Gemini 2.5 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-2.5", displayName: "Gemini 2.5",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-2.5-flash-lite", displayName: "Gemini 2.5 Flash Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: false),
        // Catalog-only — shut-down previews (still resolve for persisted model IDs)
        Record(id: "gemini-3-pro-preview", displayName: "Gemini 3 Pro (Preview, Retired)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-3-pro-image-preview", displayName: "Gemini 3 Pro Image (Preview, Retired)",
               capabilities: [.streaming, .vision, .reasoning, .imageGeneration],
               contextWindow: 65_536,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-3.1-flash-image-preview", displayName: "Gemini 3.1 Flash Image (Preview, Retired)",
               capabilities: [.streaming, .vision, .reasoning, .nativePDF, .imageGeneration],
               contextWindow: 131_072,
               maxOutputTokens: 32_768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-3.1-flash-lite-preview", displayName: "Gemini 3.1 Flash-Lite (Preview, Retired)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-3", displayName: "Gemini 3",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-3-pro", displayName: "Gemini 3 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemma-4-31b-it", displayName: "Gemma 4 31B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemma-4-26b-a4b-it", displayName: "Gemma 4 26B A4B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
    ] + veoVideoRecords

    // MARK: Vertex AI

    static let vertexAIRecords: [Record] = [
        // Seeded — live stable / current preview IDs only
        Record(id: "gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3-pro-image", displayName: "Gemini 3 Pro Image",
               capabilities: [.streaming, .vision, .reasoning, .imageGeneration],
               contextWindow: 65_536,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-image", displayName: "Gemini 3.1 Flash Image",
               capabilities: [.streaming, .vision, .reasoning, .nativePDF, .imageGeneration],
               contextWindow: 131_072,
               maxOutputTokens: 32_768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3-flash-preview", displayName: "Gemini 3 Flash (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        // GA 2026-08-13. Thinking is LOW/MEDIUM/HIGH — MINIMAL is rejected by the API.
        Record(id: "gemini-3.7-flash", displayName: "Gemini 3.7 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.6-flash", displayName: "Gemini 3.6 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.5-flash", displayName: "Gemini 3.5 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.5-flash-lite", displayName: "Gemini 3.5 Flash-Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-lite", displayName: "Gemini 3.1 Flash-Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-2.5-pro", displayName: "Gemini 2.5 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-2.5-flash-image", displayName: "Gemini 2.5 Flash Image",
               capabilities: [.streaming, .vision, .imageGeneration],
               contextWindow: 32_768,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only — shut-down previews + live non-seeded 2.5 text
        Record(id: "gemini-3-pro-preview", displayName: "Gemini 3 Pro (Preview, Retired)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-3-pro-image-preview", displayName: "Gemini 3 Pro Image (Preview, Retired)",
               capabilities: [.streaming, .vision, .reasoning, .imageGeneration],
               contextWindow: 65_536,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-3.1-flash-image-preview", displayName: "Gemini 3.1 Flash Image (Preview, Retired)",
               capabilities: [.streaming, .vision, .reasoning, .nativePDF, .imageGeneration],
               contextWindow: 131_072,
               maxOutputTokens: 32_768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-3.1-flash-lite-preview", displayName: "Gemini 3.1 Flash-Lite (Preview, Retired)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-3", displayName: "Gemini 3",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-3-pro", displayName: "Gemini 3 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-2.5", displayName: "Gemini 2.5",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-2.5-flash-lite", displayName: "Gemini 2.5 Flash Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: false),
    ] + veoVideoRecords

    // MARK: OpenRouter

    static let openRouterRecords: [Record] = [
        // Dots Studio dots3-note preview (Xiaohongshu; verified against live OpenRouter
        // /models + /endpoints, 2026-08-15, plus HF `dots-studio/dots3-note-prev` and
        // studio.dots.ai). Only the live `:free` slug (AtlasCloud fp8) is catalogued —
        // OpenRouter also documents `dots-studio/dots-3-note-preview`, but that ID has
        // no endpoints, so it stays unsupported until a provider comes up. 512,000
        // context / 512,000 max output. Input is text+image only on OpenRouter (the
        // open weights also understand audio/video; do not claim those modalities on
        // this gateway). Tools + structured outputs. Reasoning is optional
        // (mandatory=false) and toggle-only: supported_parameters list `reasoning` /
        // `include_reasoning` but not `reasoning_effort`. No cached-input pricing /
        // implicit cache. Official weights have no native-PDF contract on this
        // gateway — adapter text-fallbacks files.
        Record(id: "dots-studio/dots-3-note-preview:free", displayName: "Dots Studio: Dots3-Note Preview (Free)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 512_000,
               maxOutputTokens: 512_000,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),

        // Meta Muse Spark (OpenRouter live /models, 2026-08-06): 1M context, always-on
        // reasoning (mandatory=true, minimal..xhigh). OpenRouter chat path still
        // text-fallbacks files — claim vision/reasoning/promptCaching only.
        Record(id: "meta/muse-spark-1.2", displayName: "Meta: Muse Spark 1.2",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "meta/muse-spark-1.1", displayName: "Meta: Muse Spark 1.1",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),

        // OpenRouter: no native PDF path (adapter text-fallbacks files). Effort default
        // is `low` per OpenRouter model card; context for 4.20 family is 2M on OR.
        Record(id: "x-ai/grok-4.3", displayName: "xAI: Grok 4.3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1_000_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "x-ai/grok-4.20", displayName: "xAI: Grok 4.20",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 2_000_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "x-ai/grok-4.20-multi-agent", displayName: "xAI: Grok 4.20 Multi-Agent",
               capabilities: [.streaming, .vision, .reasoning, .promptCaching],
               contextWindow: 2_000_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "xiaomi/mimo-v2-omni", displayName: "MiMo V2 Omni",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 262_144,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "xiaomi/mimo-v2-pro", displayName: "MiMo V2 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "xiaomi/mimo-v2-flash", displayName: "MiMo V2 Flash",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 262_144,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2.7", displayName: "MiniMax M2.7",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_608,
               maxOutputTokens: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2.5:free", displayName: "MiniMax M2.5 (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_608,
               maxOutputTokens: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2-her", displayName: "MiniMax M2-her",
               capabilities: [.streaming, .promptCaching],
               contextWindow: 65_536,
               maxOutputTokens: 2_048,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2.1", displayName: "MiniMax M2.1",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2", displayName: "MiniMax M2",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 196_608,
               maxOutputTokens: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m1", displayName: "MiniMax M1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 40_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-01", displayName: "MiniMax-01",
               capabilities: [.streaming, .vision],
               contextWindow: 1_000_192,
               maxOutputTokens: 1_000_192,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        // OpenRouter currently reports `context_length: 0` for async video models.
        // Keep a conservative placeholder until provider docs expose a prompt window.
        Record(id: "bytedance/seedance-1-5-pro", displayName: "Seedance 1.5 Pro",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "bytedance/seedance-2.0", displayName: "Seedance 2.0",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "bytedance/seedance-2.0-fast", displayName: "Seedance 2.0 Fast",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        // OpenRouter video model: durations 4–30s, 480p/720p, first/last frame + references.
        Record(id: "bytedance/seedance-2.5", displayName: "Seedance 2.5",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.4-image-2", displayName: "GPT-5.4 Image 2",
               capabilities: [.streaming, .vision, .reasoning, .promptCaching, .imageGeneration],
               contextWindow: 272_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "deepseek/deepseek-v4-flash", displayName: "DeepSeek V4 Flash",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 384_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "deepseek/deepseek-v4-pro", displayName: "DeepSeek V4 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 384_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3-pro-preview", displayName: "Gemini 3 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.1-flash-lite-preview", displayName: "Gemini 3.1 Flash-Lite (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.1-flash-lite", displayName: "Gemini 3.1 Flash-Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.7-flash", displayName: "Gemini 3.7 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.6-flash", displayName: "Gemini 3.6 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.5-flash", displayName: "Gemini 3.5 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.5-flash-lite", displayName: "Gemini 3.5 Flash-Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: false),
        Record(id: "moonshotai/kimi-k2.6", displayName: "Kimi K2.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        // Kimi K3 (verified against live OpenRouter /models metadata, 2026-07-18):
        // 1,048,576 context, text+image->text, cached-input pricing. Reasoning is
        // mandatory with supported_efforts = ["max"] only, so reasoningConfig stays
        // nil — Jin sends no reasoning shape and OpenRouter applies its default max
        // effort (same pattern as the `k3` Kimi for Coding record, including leaving
        // the always-on resolver default moot). Moonshot documents
        // max_completion_tokens up to the full window with a 131,072 default while
        // OpenRouter reports no provider cap, so maxOutputTokens stays conservative.
        Record(id: "moonshotai/kimi-k3", displayName: "Kimi K3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        // Thinking Machines Inkling (open-weight MoE; verified against live OpenRouter
        // /models metadata, 2026-07-18): 1,048,576 model-level context (the sole
        // inference provider currently caps requests at 524,288), text+image+audio->text,
        // cached-input pricing. Reasoning is on by default (default_effort "high") with
        // a none/minimal/low/medium/high/max band and no xhigh — see
        // ModelCapabilityRegistry.openRouterMinimalMaxEffortModelIDs. Max output is
        // undocumented by both Thinking Machines and OpenRouter, so it stays unset.
        Record(id: "thinkingmachines/inkling", displayName: "Thinking Machines: Inkling",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemma-4-31b-it", displayName: "Gemma 4 31B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemma-4-26b-a4b-it", displayName: "Gemma 4 26B A4B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        // MARK: New OpenRouter models (verified against OpenRouter /models, 2026-06)
        Record(id: "nvidia/nemotron-3.5-content-safety:free", displayName: "NVIDIA: Nemotron 3.5 Content Safety (Free)",
               capabilities: [.streaming, .vision, .reasoning],
               contextWindow: 128000,
               maxOutputTokens: 8192,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "nvidia/nemotron-3-ultra-550b-a55b:free", displayName: "NVIDIA: Nemotron 3 Ultra (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1000000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.7-plus", displayName: "Qwen: Qwen3.7 Plus",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m3", displayName: "MiniMax: MiniMax M3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1048576,
               maxOutputTokens: 512000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "stepfun/step-3.7-flash", displayName: "StepFun: Step 3.7 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 256000,
               maxOutputTokens: 256000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        // Opus 5 on OpenRouter keeps the undotted upstream ID (`anthropic/claude-opus-5`),
        // unlike the dotted 4.x aliases. Live /models metadata (2026-07-25): 1,000,000 context /
        // 128,000 output, efforts low…max defaulting to high, reasoning.mandatory=false with
        // default_enabled=true — so it is deliberately NOT in `openRouterAlwaysOnReasoningModelIDs`.
        Record(id: "anthropic/claude-opus-5-fast", displayName: "Anthropic: Claude Opus 5 (Fast)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-5", displayName: "Anthropic: Claude Opus 5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4.8-fast", displayName: "Anthropic: Claude Opus 4.8 (Fast)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4.8", displayName: "Anthropic: Claude Opus 4.8",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.7-max", displayName: "Qwen: Qwen3.7 Max",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "x-ai/grok-build-0.1", displayName: "xAI: Grok Build 0.1",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 256000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4.7-fast", displayName: "Anthropic: Claude Opus 4.7 (Fast)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "openrouter/fusion", displayName: "OpenRouter: Fusion",
               capabilities: [.streaming],
               contextWindow: 128000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "perceptron/perceptron-mk1", displayName: "Perceptron: Perceptron Mk1",
               capabilities: [.streaming, .vision, .reasoning],
               contextWindow: 32768,
               maxOutputTokens: 8192,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "inclusionai/ring-2.6-1t", displayName: "inclusionAI: Ring-2.6-1T",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 262144,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-chat-latest", displayName: "OpenAI: GPT Chat (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .promptCaching],
               contextWindow: 400000,
               maxOutputTokens: 128000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "ibm-granite/granite-4.1-8b", displayName: "IBM: Granite 4.1 8B",
               capabilities: [.streaming, .toolCalling, .promptCaching],
               contextWindow: 131072,
               maxOutputTokens: 131072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "mistralai/mistral-medium-3-5", displayName: "Mistral: Mistral Medium 3.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "openrouter/owl-alpha", displayName: "OpenRouter: Owl Alpha",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 1048576,
               maxOutputTokens: 262144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", displayName: "NVIDIA: Nemotron 3 Nano Omni (Free)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning],
               contextWindow: 256000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "poolside/laguna-xs.2:free", displayName: "Poolside: Laguna XS.2 (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "poolside/laguna-m.1:free", displayName: "Poolside: Laguna M.1 (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "~anthropic/claude-haiku-latest", displayName: "Anthropic: Claude Haiku (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 200000,
               maxOutputTokens: 64000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "~openai/gpt-mini-latest", displayName: "OpenAI: GPT Mini (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "~google/gemini-pro-latest", displayName: "Google: Gemini Pro (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1048576,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "~moonshotai/kimi-latest", displayName: "MoonshotAI: Kimi (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 262144,
               maxOutputTokens: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "~google/gemini-flash-latest", displayName: "Google: Gemini Flash (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1048576,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "~anthropic/claude-sonnet-latest", displayName: "Anthropic: Claude Sonnet (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "~openai/gpt-latest", displayName: "OpenAI: GPT (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1050000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.5-plus-20260420", displayName: "Qwen: Qwen3.5 Plus 2026-04-20",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1000000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.6-flash", displayName: "Qwen: Qwen3.6 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1000000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.6-35b-a3b", displayName: "Qwen: Qwen3.6 35B A3B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 262140,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.6-max-preview", displayName: "Qwen: Qwen3.6 Max Preview",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.6-27b", displayName: "Qwen: Qwen3.6 27B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 262140,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.5-pro", displayName: "OpenAI: GPT-5.5 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1050000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.5", displayName: "OpenAI: GPT-5.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1050000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "inclusionai/ling-2.6-1t", displayName: "inclusionAI: Ling-2.6-1T",
               capabilities: [.streaming, .toolCalling, .promptCaching],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "tencent/hy3-preview", displayName: "Tencent: Hy3 Preview",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "xiaomi/mimo-v2.5-pro", displayName: "Xiaomi: MiMo-V2.5-Pro",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1048576,
               maxOutputTokens: 131072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "xiaomi/mimo-v2.5", displayName: "Xiaomi: MiMo-V2.5",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1048576,
               maxOutputTokens: 131072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "inclusionai/ling-2.6-flash", displayName: "inclusionAI: Ling-2.6-flash",
               capabilities: [.streaming, .toolCalling, .promptCaching],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "~anthropic/claude-opus-latest", displayName: "Anthropic: Claude Opus (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "openrouter/pareto-code", displayName: "OpenRouter: Pareto Code",
               capabilities: [.streaming],
               contextWindow: 2000000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "moonshotai/kimi-k2.6:free", displayName: "MoonshotAI: Kimi K2.6 (Free)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4.7", displayName: "Anthropic: Claude Opus 4.7",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4.6-fast", displayName: "Anthropic: Claude Opus 4.6 (Fast)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "z-ai/glm-5.2", displayName: "Z.ai: GLM 5.2",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1048576,
               maxOutputTokens: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "z-ai/glm-5.1", displayName: "Z.ai: GLM 5.1",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 202752,
               maxOutputTokens: 131072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemma-4-26b-a4b-it:free", displayName: "Google: Gemma 4 26B A4B (Free)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemma-4-31b-it:free", displayName: "Google: Gemma 4 31B (Free)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.6-plus", displayName: "Qwen: Qwen3.6 Plus",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1000000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "z-ai/glm-5v-turbo", displayName: "Z.ai: GLM 5V Turbo",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 202752,
               maxOutputTokens: 131072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "arcee-ai/trinity-large-thinking", displayName: "Arcee AI: Trinity Large Thinking",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 262144,
               maxOutputTokens: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "kwaipilot/kat-coder-pro-v2", displayName: "Kwaipilot: KAT-Coder-Pro V2",
               capabilities: [.streaming, .toolCalling, .promptCaching],
               contextWindow: 256000,
               maxOutputTokens: 80000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "rekaai/reka-edge", displayName: "Reka AI: Reka Edge",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 16384,
               maxOutputTokens: 16384,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.4-nano", displayName: "OpenAI: GPT-5.4 Nano",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.4-mini", displayName: "OpenAI: GPT-5.4 Mini",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "mistralai/mistral-small-2603", displayName: "Mistral: Mistral Small 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "z-ai/glm-5-turbo", displayName: "Z.ai: GLM 5 Turbo",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 202752,
               maxOutputTokens: 131072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        // MARK: New OpenRouter models (verified against OpenRouter /models + /endpoints, 2026-07-11)
        // Capability ceiling: the OpenRouter adapter drops video input and text-fallbacks
        // PDFs, so these records never claim .videoInput/.nativePDF/.codeExecution.
        // GPT-5.6 Sol/Terra/Luna (created 2026-07-09): 1.05M ctx / 128K out, efforts
        // none..max default medium; the -pro twins are the same models served with
        // OpenAI's reasoning.mode=pro at identical listed pricing.
        Record(id: "openai/gpt-5.6-sol", displayName: "OpenAI: GPT-5.6 Sol",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1050000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.6-sol-pro", displayName: "OpenAI: GPT-5.6 Sol Pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1050000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.6-terra", displayName: "OpenAI: GPT-5.6 Terra",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1050000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.6-terra-pro", displayName: "OpenAI: GPT-5.6 Terra Pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1050000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.6-luna", displayName: "OpenAI: GPT-5.6 Luna",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1050000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.6-luna-pro", displayName: "OpenAI: GPT-5.6 Luna Pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1050000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        // Grok 4.6 (created 2026-08-12): 500K ctx, max output unpublished
        // (max_completion_tokens null), reasoning mandatory low/medium/high/xhigh
        // default high (docs.x.ai + OpenRouter /models). nativePDF kept off on
        // OpenRouter (gateway PDF modality is not guaranteed).
        Record(id: "x-ai/grok-4.6", displayName: "xAI: Grok 4.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 500000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        // Grok 4.5 (created 2026-07-08): 500K ctx, max output unpublished
        // (max_completion_tokens null), reasoning mandatory low/medium/high default high.
        // nativePDF kept off on OpenRouter (gateway PDF modality is not guaranteed).
        Record(id: "x-ai/grok-4.5", displayName: "xAI: Grok 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 500000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        // Claude Sonnet 5 arrived on OpenRouter 2026-06-30 (it was deliberately NOT added
        // when the native record shipped, pending live confirmation — now confirmed).
        // OpenRouter reports efforts low..max with default medium.
        Record(id: "anthropic/claude-sonnet-5", displayName: "Anthropic: Claude Sonnet 5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-fable-5", displayName: "Anthropic: Claude Fable 5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        // Tencent Hy3 (created 2026-07-06): reasoning default-DISABLED with efforts
        // high/low/none; paid route publishes no max output, the free route allows the
        // full 262K. Text-only.
        Record(id: "tencent/hy3", displayName: "Tencent: Hy3",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "tencent/hy3:free", displayName: "Tencent: Hy3 (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        // Poolside Laguna XS 2.1 (created 2026-07-02): reasoning is a plain toggle —
        // no reasoning_effort in supported_parameters.
        Record(id: "poolside/laguna-xs-2.1", displayName: "Poolside: Laguna XS 2.1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        Record(id: "poolside/laguna-xs-2.1:free", displayName: "Poolside: Laguna XS 2.1 (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
        // AionLabs Aion-3.0 (created 2026-07-07): reasoning is mandatory with no effort
        // control, so no reasoningConfig is exposed.
        Record(id: "aion-labs/aion-3.0", displayName: "AionLabs: Aion-3.0",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 131072,
               maxOutputTokens: 32768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        // Gemini 3.1 Flash Lite Image "Nano Banana 2 Lite" (created 2026-06-30): image
        // OUTPUT, no tools on OpenRouter, efforts minimal/high default minimal.
        Record(id: "google/gemini-3.1-flash-lite-image", displayName: "Google: Gemini 3.1 Flash Lite Image",
               capabilities: [.streaming, .vision, .reasoning, .imageGeneration],
               contextWindow: 65536,
               maxOutputTokens: 66000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: false),
        // Sakana Fugu Ultra (created 2026-06-24): learned multi-agent orchestration
        // system; efforts restricted to high/xhigh/max, default xhigh.
        Record(id: "sakana/fugu-ultra", displayName: "Sakana: Fugu Ultra",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .xhigh),
               isFullySupported: true, isSeeded: false),
        // Nex AGI Nex-N2-Mini (created 2026-06-24): reasoning is a plain toggle.
        Record(id: "nex-agi/nex-n2-mini", displayName: "Nex AGI: Nex-N2-Mini",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 262144,
               reasoningConfig: ModelReasoningConfig(type: .toggle),
               isFullySupported: true, isSeeded: false),
    ]
}
