import Foundation

// MARK: - Gemini, Vertex AI & OpenRouter Records

extension ModelCatalog {

    // MARK: Shared Veo Video-Generation Records

    /// Veo model records shared between the Gemini (AI Studio) and Vertex AI catalogs.
    private static let veoVideoRecords: [Record] = [
        Record(id: "veo-2", displayName: "Veo 2",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-3", displayName: "Veo 3",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-3.1-generate-preview", displayName: "Veo 3.1 (Preview)",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-3.1-fast-generate-preview", displayName: "Veo 3.1 Fast (Preview)",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-3.1-lite-generate-preview", displayName: "Veo 3.1 Lite (Preview)",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-3.0-generate-001", displayName: "Veo 3",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-3.0-fast-generate-001", displayName: "Veo 3 Fast",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "veo-2.0-generate-001", displayName: "Veo 2",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
    ]


    // MARK: Gemini (AI Studio)

    static let geminiRecords: [Record] = [
        // Seeded
        Record(id: "gemini-3-pro-preview", displayName: "Gemini 3 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3-pro-image-preview", displayName: "Gemini 3 Pro Image (Preview)",
               capabilities: [.streaming, .vision, .reasoning, .imageGeneration],
               contextWindow: 65_536,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-image-preview", displayName: "Gemini 3.1 Flash Image (Preview)",
               capabilities: [.streaming, .vision, .reasoning, .nativePDF, .imageGeneration],
               contextWindow: 131_072,
               maxOutputTokens: 32_768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3-flash-preview", displayName: "Gemini 3 Flash (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.5-flash", displayName: "Gemini 3.5 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-lite-preview", displayName: "Gemini 3.1 Flash-Lite (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-lite", displayName: "Gemini 3.1 Flash-Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-2.5-flash-image", displayName: "Gemini 2.5 Flash Image",
               capabilities: [.streaming, .vision, .imageGeneration],
               contextWindow: 65_536,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "gemini-3", displayName: "Gemini 3",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-3-pro", displayName: "Gemini 3 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemma-4-31b-it", displayName: "Gemma 4 31B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemma-4-26b-a4b-it", displayName: "Gemma 4 26B A4B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
    ] + veoVideoRecords

    // MARK: Vertex AI

    static let vertexAIRecords: [Record] = [
        // Seeded
        Record(id: "gemini-3-pro-preview", displayName: "Gemini 3 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3-pro-image-preview", displayName: "Gemini 3 Pro Image (Preview)",
               capabilities: [.streaming, .vision, .reasoning, .imageGeneration],
               contextWindow: 65_536,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-image-preview", displayName: "Gemini 3.1 Flash Image (Preview)",
               capabilities: [.streaming, .vision, .reasoning, .nativePDF, .imageGeneration],
               contextWindow: 131_072,
               maxOutputTokens: 32_768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3-flash-preview", displayName: "Gemini 3 Flash (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.5-flash", displayName: "Gemini 3.5 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-3.1-flash-lite-preview", displayName: "Gemini 3.1 Flash-Lite (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-2.5-pro", displayName: "Gemini 2.5 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: true),
        Record(id: "gemini-2.5-flash-image", displayName: "Gemini 2.5 Flash Image",
               capabilities: [.streaming, .vision, .imageGeneration],
               contextWindow: 32_768,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: true),
        // Catalog-only
        Record(id: "gemini-3", displayName: "Gemini 3",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-3-pro", displayName: "Gemini 3 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-2.5", displayName: "Gemini 2.5",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: true, isSeeded: false),
        Record(id: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: false, isSeeded: false),
        Record(id: "gemini-2.5-flash-lite", displayName: "Gemini 2.5 Flash Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching, .nativePDF, .codeExecution],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_535,
               reasoningConfig: ModelReasoningConfig(type: .budget, defaultBudget: 2048),
               isFullySupported: false, isSeeded: false),
    ] + veoVideoRecords

    // MARK: OpenRouter

    static let openRouterRecords: [Record] = [
        Record(id: "x-ai/grok-4.3", displayName: "xAI: Grok 4.3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1_000_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "x-ai/grok-4.20", displayName: "xAI: Grok 4.20",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 2_000_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "x-ai/grok-4.20-multi-agent", displayName: "xAI: Grok 4.20 Multi-Agent",
               capabilities: [.streaming, .vision, .reasoning, .promptCaching, .nativePDF],
               contextWindow: 2_000_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "xiaomi/mimo-v2-omni", displayName: "MiMo V2 Omni",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 262_144,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "xiaomi/mimo-v2-pro", displayName: "MiMo V2 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "xiaomi/mimo-v2-flash", displayName: "MiMo V2 Flash",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 262_144,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2.7", displayName: "MiniMax M2.7",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 204_800,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2.5", displayName: "MiniMax M2.5",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_608,
               maxOutputTokens: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2.5:free", displayName: "MiniMax M2.5 (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_608,
               maxOutputTokens: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2-her", displayName: "MiniMax M2-her",
               capabilities: [.streaming, .promptCaching],
               contextWindow: 65_536,
               maxOutputTokens: 2_048,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2.1", displayName: "MiniMax M2.1",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m2", displayName: "MiniMax M2",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 196_608,
               maxOutputTokens: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m1", displayName: "MiniMax M1",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 40_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-01", displayName: "MiniMax-01",
               capabilities: [.streaming, .vision],
               contextWindow: 1_000_192,
               maxOutputTokens: 1_000_192,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        // OpenRouter currently reports `context_length: 0` for async video models.
        // Keep a conservative placeholder until provider docs expose a prompt window.
        Record(id: "bytedance/seedance-1-5-pro", displayName: "Seedance 1.5 Pro",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "bytedance/seedance-2.0", displayName: "Seedance 2.0",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "bytedance/seedance-2.0-fast", displayName: "Seedance 2.0 Fast",
               capabilities: [.videoGeneration],
               contextWindow: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.4-image-2", displayName: "GPT-5.4 Image 2",
               capabilities: [.streaming, .vision, .reasoning, .promptCaching, .imageGeneration],
               contextWindow: 272_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "deepseek/deepseek-v4-flash", displayName: "DeepSeek V4 Flash",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 384_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "deepseek/deepseek-v4-pro", displayName: "DeepSeek V4 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 384_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3-pro-preview", displayName: "Gemini 3 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.1-flash-lite-preview", displayName: "Gemini 3.1 Flash-Lite (Preview)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.1-flash-lite", displayName: "Gemini 3.1 Flash-Lite",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .minimal),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemini-3.5-flash", displayName: "Gemini 3.5 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1_048_576,
               maxOutputTokens: 65_536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "moonshotai/kimi-k2.6", displayName: "Kimi K2.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemma-4-31b-it", displayName: "Gemma 4 31B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemma-4-26b-a4b-it", displayName: "Gemma 4 26B A4B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        // MARK: New OpenRouter models (verified against OpenRouter /models, 2026-06)
        Record(id: "nvidia/nemotron-3.5-content-safety:free", displayName: "NVIDIA: Nemotron 3.5 Content Safety (Free)",
               capabilities: [.streaming, .vision, .reasoning],
               contextWindow: 128000,
               maxOutputTokens: 8192,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "nvidia/nemotron-3-ultra-550b-a55b:free", displayName: "NVIDIA: Nemotron 3 Ultra (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1000000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.7-plus", displayName: "Qwen: Qwen3.7 Plus",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "minimax/minimax-m3", displayName: "MiniMax: MiniMax M3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1048576,
               maxOutputTokens: 512000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "stepfun/step-3.7-flash", displayName: "StepFun: Step 3.7 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 256000,
               maxOutputTokens: 256000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4.8-fast", displayName: "Anthropic: Claude Opus 4.8 (Fast)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4.8", displayName: "Anthropic: Claude Opus 4.8",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.7-max", displayName: "Qwen: Qwen3.7 Max",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "x-ai/grok-build-0.1", displayName: "xAI: Grok Build 0.1",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 256000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4.7-fast", displayName: "Anthropic: Claude Opus 4.7 (Fast)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "openrouter/fusion", displayName: "OpenRouter: Fusion",
               capabilities: [.streaming],
               contextWindow: 128000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "perceptron/perceptron-mk1", displayName: "Perceptron: Perceptron Mk1",
               capabilities: [.streaming, .vision, .reasoning],
               contextWindow: 32768,
               maxOutputTokens: 8192,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "inclusionai/ring-2.6-1t", displayName: "inclusionAI: Ring-2.6-1T",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 262144,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-chat-latest", displayName: "OpenAI: GPT Chat (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .promptCaching],
               contextWindow: 400000,
               maxOutputTokens: 128000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "ibm-granite/granite-4.1-8b", displayName: "IBM: Granite 4.1 8B",
               capabilities: [.streaming, .toolCalling, .promptCaching],
               contextWindow: 131072,
               maxOutputTokens: 131072,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "mistralai/mistral-medium-3-5", displayName: "Mistral: Mistral Medium 3.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "openrouter/owl-alpha", displayName: "OpenRouter: Owl Alpha",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 1048576,
               maxOutputTokens: 262144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", displayName: "NVIDIA: Nemotron 3 Nano Omni (Free)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning],
               contextWindow: 256000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "poolside/laguna-xs.2:free", displayName: "Poolside: Laguna XS.2 (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "poolside/laguna-m.1:free", displayName: "Poolside: Laguna M.1 (Free)",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "~anthropic/claude-haiku-latest", displayName: "Anthropic: Claude Haiku (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 200000,
               maxOutputTokens: 64000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "~openai/gpt-mini-latest", displayName: "OpenAI: GPT Mini (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "~google/gemini-pro-latest", displayName: "Google: Gemini Pro (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1048576,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "~moonshotai/kimi-latest", displayName: "MoonshotAI: Kimi (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 262144,
               maxOutputTokens: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "~google/gemini-flash-latest", displayName: "Google: Gemini Flash (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1048576,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "~anthropic/claude-sonnet-latest", displayName: "Anthropic: Claude Sonnet (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "~openai/gpt-latest", displayName: "OpenAI: GPT (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1050000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.5-plus-20260420", displayName: "Qwen: Qwen3.5 Plus 2026-04-20",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1000000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.6-flash", displayName: "Qwen: Qwen3.6 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1000000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.6-35b-a3b", displayName: "Qwen: Qwen3.6 35B A3B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 262140,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.6-max-preview", displayName: "Qwen: Qwen3.6 Max Preview",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.6-27b", displayName: "Qwen: Qwen3.6 27B",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 262140,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.5-pro", displayName: "OpenAI: GPT-5.5 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1050000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.5", displayName: "OpenAI: GPT-5.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1050000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "inclusionai/ling-2.6-1t", displayName: "inclusionAI: Ling-2.6-1T",
               capabilities: [.streaming, .toolCalling, .promptCaching],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "tencent/hy3-preview", displayName: "Tencent: Hy3 Preview",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "xiaomi/mimo-v2.5-pro", displayName: "Xiaomi: MiMo-V2.5-Pro",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 1048576,
               maxOutputTokens: 131072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "xiaomi/mimo-v2.5", displayName: "Xiaomi: MiMo-V2.5",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning, .promptCaching],
               contextWindow: 1048576,
               maxOutputTokens: 131072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "inclusionai/ling-2.6-flash", displayName: "inclusionAI: Ling-2.6-flash",
               capabilities: [.streaming, .toolCalling, .promptCaching],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "~anthropic/claude-opus-latest", displayName: "Anthropic: Claude Opus (Latest)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "openrouter/pareto-code", displayName: "OpenRouter: Pareto Code",
               capabilities: [.streaming],
               contextWindow: 2000000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "moonshotai/kimi-k2.6:free", displayName: "MoonshotAI: Kimi K2.6 (Free)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4.7", displayName: "Anthropic: Claude Opus 4.7",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "anthropic/claude-opus-4.6-fast", displayName: "Anthropic: Claude Opus 4.6 (Fast)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 1000000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "z-ai/glm-5.1", displayName: "Z.ai: GLM 5.1",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 202752,
               maxOutputTokens: 131072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemma-4-26b-a4b-it:free", displayName: "Google: Gemma 4 26B A4B (Free)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "google/gemma-4-31b-it:free", displayName: "Google: Gemma 4 31B (Free)",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262144,
               maxOutputTokens: 32768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "qwen/qwen3.6-plus", displayName: "Qwen: Qwen3.6 Plus",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1000000,
               maxOutputTokens: 65536,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "z-ai/glm-5v-turbo", displayName: "Z.ai: GLM 5V Turbo",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 202752,
               maxOutputTokens: 131072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
        Record(id: "arcee-ai/trinity-large-thinking", displayName: "Arcee AI: Trinity Large Thinking",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 262144,
               maxOutputTokens: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "kwaipilot/kat-coder-pro-v2", displayName: "Kwaipilot: KAT-Coder-Pro V2",
               capabilities: [.streaming, .toolCalling, .promptCaching],
               contextWindow: 256000,
               maxOutputTokens: 80000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "rekaai/reka-edge", displayName: "Reka AI: Reka Edge",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 16384,
               maxOutputTokens: 16384,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.4-nano", displayName: "OpenAI: GPT-5.4 Nano",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-5.4-mini", displayName: "OpenAI: GPT-5.4 Mini",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 400000,
               maxOutputTokens: 128000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "mistralai/mistral-small-2603", displayName: "Mistral: Mistral Small 4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning, .promptCaching],
               contextWindow: 262144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "z-ai/glm-5-turbo", displayName: "Z.ai: GLM 5 Turbo",
               capabilities: [.streaming, .toolCalling, .reasoning, .promptCaching],
               contextWindow: 202752,
               maxOutputTokens: 131072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .low),
               isFullySupported: true, isSeeded: false),
    ]
}
