import Foundation

// MARK: - Router (Ramp) Records
//
// Router is Responses-only: `POST /v1/responses` is the sole completion route and
// `POST /v1/chat/completions` 404s. Every field below is transcribed from a live
// `GET /v1/models` on 2026-08-22 — `limits.{context_window,max_output_tokens}`,
// `capabilities.modalities.input`, `.tools.supported` and `.reasoning.{efforts,
// default_effort}`. Do NOT source these from docs.router.com/supported-models: that
// table is explicitly display-only and its labels are not callable model IDs
// ("opus-5" is really "claude-opus-5"; "kimi-k3" is really
// "accounts/fireworks/models/kimi-k3").
//
// Router's per-model effort bands are enforced, not clamped — an unsupported value
// returns `400 Invalid reasoning effort.` The matching bands live in
// ModelCapabilityRegistry.supportedReasoningEfforts.
//
// The 7 models Router reports as `status: "deprecated"` (gpt-3.5-turbo, gpt-4,
// gpt-4-turbo, gpt-4.1-nano, o1, o3-mini, o4-mini) are deliberately not bundled;
// OpenAI shuts them down 2026-10-23. A key that still has them picks them up from
// the live fetch.

extension ModelCatalog {

    static let routerRecords: [Record] = [
        // MARK: Anthropic
        Record(id: "claude-fable-5", displayName: "Claude Fable 5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        // Router supported-models table (docs.router.com, fetched 2026-09-20):
        // label `fable-5-1` under [Anthropic] — callable ID keeps the `claude-`
        // prefix like its sibling (`fable-5` → `claude-fable-5`). Table band is
        // minimal..max (routerMinimalToMaxEffortModelIDs), 1,000,000 / 128,000.
        Record(id: "claude-fable-5-1", displayName: "Claude Fable 5.1",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "claude-haiku-4-5", displayName: "Claude Haiku 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 200_000,
               maxOutputTokens: 64_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-opus-4-6", displayName: "Claude Opus 4.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "claude-opus-4-7", displayName: "Claude Opus 4.7",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "claude-opus-4-8", displayName: "Claude Opus 4.8",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "claude-opus-5", displayName: "Claude Opus 5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "claude-sonnet-4-6", displayName: "Claude Sonnet 4.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "claude-sonnet-5", displayName: "Claude Sonnet 5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        // MARK: OpenAI
        Record(id: "gpt-4.1", displayName: "GPT-4.1",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 1_047_576,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-4.1-mini", displayName: "GPT-4.1 mini",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 1_047_576,
               maxOutputTokens: 32_768,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-4o", displayName: "GPT-4o",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 128_000,
               maxOutputTokens: 16_384,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-4o-mini", displayName: "GPT-4o mini",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 128_000,
               maxOutputTokens: 16_384,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5", displayName: "GPT-5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5-mini", displayName: "GPT-5 mini",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5-nano", displayName: "GPT-5 nano",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5-pro", displayName: "GPT-5 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 400_000,
               maxOutputTokens: 272_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5.1", displayName: "GPT-5.1",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5.2", displayName: "GPT-5.2",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5.2-pro", displayName: "GPT-5.2 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5.3-codex", displayName: "GPT-5.3-Codex",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5.4", displayName: "GPT-5.4",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_050_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.4-mini", displayName: "GPT-5.4 mini",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5.4-nano", displayName: "GPT-5.4 nano",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 400_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5.4-pro", displayName: "GPT-5.4 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_050_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5.5", displayName: "GPT-5.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_050_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5.5-pro", displayName: "GPT-5.5 Pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_050_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "gpt-5.6-luna", displayName: "GPT-5.6 Luna",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_050_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.6-sol", displayName: "GPT-5.6 Sol",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_050_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "gpt-5.6-terra", displayName: "GPT-5.6 Terra",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_050_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        // Router supported-models table (fetched 2026-09-20): `gpt-6-astra`,
        // Fast mode Available, 1,050,000 / 128,000, effort band
        // low/medium/high/xhigh/max — no `none`, no `minimal`
        // (routerLowToMaxEffortModelIDs).
        Record(id: "gpt-6-astra", displayName: "GPT-6 Astra",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_050_000,
               maxOutputTokens: 128_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "o3", displayName: "o3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 200_000,
               maxOutputTokens: 100_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "o3-pro", displayName: "o3-pro",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 200_000,
               maxOutputTokens: 100_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        // MARK: xAI
        Record(id: "grok-4.20-0309-non-reasoning", displayName: "Grok 4.20 (Non-Reasoning)",
               capabilities: [.streaming, .toolCalling, .vision],
               contextWindow: 1_000_000,
               maxOutputTokens: 1_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-4.20-0309-reasoning", displayName: "Grok 4.20",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 1_000_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-4.20-multi-agent-0309", displayName: "Grok 4.20 Multi-Agent Beta",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 1_000_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-4.3", displayName: "Grok 4.3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 1_000_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "grok-4.5", displayName: "Grok 4.5",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 500_000,
               maxOutputTokens: 500_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        // grok-4.7 (docs.router.com/supported-models, 2026-09-22). Callable ID
        // is the bare slug. 500,000 context and 500,000 max output are the
        // published Router columns (xAI itself publishes no output cap).
        // Reasoning efforts are low/medium/high/xhigh — Router drops the
        // `minimal` it still lists for grok-4.6.
        Record(id: "grok-4.7", displayName: "Grok 4.7",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 500_000,
               maxOutputTokens: 500_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-4.6", displayName: "Grok 4.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 500_000,
               maxOutputTokens: 500_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "grok-build-0.1", displayName: "Grok Build 0.1",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 256_000,
               maxOutputTokens: 256_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        // MARK: Fireworks
        Record(id: "accounts/fireworks/models/deepseek-v4-flash", displayName: "DeepSeek-V4-Flash",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/deepseek-v4-flash-0731", displayName: "DeepSeek-V4-Flash-0731",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        // Router "Supported Models" table (docs.router.com, verified 2026-09-12):
        // label `deepseek-v4p1-flash` under the DeepSeek section — same Fireworks
        // path scheme as siblings. Table publishes 1,048,576 ctx / 1,048,576 max
        // out and the none/minimal/low/medium/high/xhigh effort band
        // (routerNoneToExtremeEffortModelIDs). Vision is not claimed — the table
        // does not publish modality.
        Record(id: "accounts/fireworks/models/deepseek-v4p1-flash", displayName: "DeepSeek-V4.1-Flash",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/deepseek-v4-pro", displayName: "DeepSeek-V4-Pro",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 384_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: true),
        Record(id: "accounts/fireworks/models/deepseek-v4-pro-0813", displayName: "DeepSeek-V4-Pro-0813",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 384_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/glm-5p3", displayName: "GLM 5.3",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .max),
               isFullySupported: true, isSeeded: true),
        Record(id: "accounts/fireworks/routers/glm-5p3-fast", displayName: "GLM 5.3 Fast",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .max),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/glm-5p2", displayName: "GLM 5.2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .xhigh),
               isFullySupported: true, isSeeded: true),
        Record(id: "accounts/fireworks/models/gpt-oss-120b", displayName: "OpenAI gpt-oss-120b",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 131_072,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "accounts/fireworks/models/gpt-oss-20b", displayName: "OpenAI gpt-oss-20b",
               capabilities: [.streaming, .reasoning],
               contextWindow: 131_072,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/kimi-k2p6", displayName: "Kimi K2.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/kimi-k2p7-code", displayName: "Kimi K2.7 Code",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/kimi-k3", displayName: "Kimi K3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: true),
        Record(id: "accounts/fireworks/models/minimax-m2p7", displayName: "MiniMax M2.7",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 196_608,
               maxOutputTokens: 196_608,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/minimax-m3", displayName: "Minimax M3",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 512_000,
               maxOutputTokens: 512_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "accounts/fireworks/models/nemotron-3-ultra-nvfp4", displayName: "NVIDIA Nemotron 3 Ultra NVFP4",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/qwen3p7-plus", displayName: "Qwen3.7 Plus",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/models/qwen3p8-max", displayName: "Qwen 3.8 Max",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_000_000,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: true),
        Record(id: "accounts/fireworks/routers/glm-5p2-fast", displayName: "GLM 5.2 Fast",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .xhigh),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/routers/kimi-k2p6-turbo", displayName: "Kimi K2.6 Fast",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/routers/kimi-k2p7-code-fast", displayName: "Kimi K2.7 Code Fast",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "accounts/fireworks/routers/kimi-k3-fast", displayName: "Kimi K3 Fast",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        // Router supported-models table (fetched 2026-09-20): label `glm-5p3-flash`
        // under [Z.ai] — same Fireworks path scheme as `glm-5p3`. Band is
        // minimal..max (routerMinimalToMaxEffortModelIDs), 1,048,576 / 1,048,576.
        Record(id: "accounts/fireworks/models/glm-5p3-flash", displayName: "GLM 5.3 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .max),
               isFullySupported: true, isSeeded: false),
        // Label `nemotron-lightning-3p5-30b-a3b` under [NVIDIA] — Nemotron Lightning
        // 3.5 30B-A3B (the 30B Flash variant, NOT the 1M `nemotron-3-5-lightning`).
        // Table: 262,144 / 262,144, reasoning Not supported.
        Record(id: "accounts/fireworks/models/nemotron-lightning-3p5-30b-a3b", displayName: "Nemotron Lightning 3.5 30B A3B",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 262_144,
               maxOutputTokens: 262_144,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        // MARK: Baseten backend
        // Second table group on docs.router.com/supported-models publishes upstream
        // Hugging Face-style IDs verbatim (`deepseek-ai/DeepSeek-V4.1-Flash`, not the
        // `accounts/fireworks/…` path). These are a distinct backend — bands below are
        // the published per-model rows, NOT the Fireworks copies' bands.
        Record(id: "deepseek-ai/DeepSeek-V4.1-Flash", displayName: "DeepSeek V4.1 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 32_768,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "deepseek-ai/DeepSeek-V4-Flash-0731", displayName: "DeepSeek V4 Flash 0731",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "deepseek-ai/DeepSeek-V4-Pro-0813", displayName: "DeepSeek V4 Pro 0813",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 384_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "deepseek-ai/DeepSeek-V4-Pro", displayName: "DeepSeek V4 Pro",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 384_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-org/GLM-5.3-Flash", displayName: "GLM 5.3 Flash",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 131_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-org/GLM-5.2-Fast", displayName: "GLM 5.2 Fast",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-org/GLM-5.2", displayName: "GLM 5.2",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "zai-org/GLM-4.7", displayName: "GLM 4.7",
               capabilities: [.streaming, .toolCalling],
               contextWindow: 200_000,
               maxOutputTokens: 200_000,
               reasoningConfig: nil,
               isFullySupported: true, isSeeded: false),
        Record(id: "moonshotai/Kimi-K3", displayName: "Kimi K3",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "moonshotai/Kimi-K2.7-Code", displayName: "Kimi K2.7 Code",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_000,
               maxOutputTokens: 262_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
        Record(id: "moonshotai/Kimi-K2.6", displayName: "Kimi K2.6",
               capabilities: [.streaming, .toolCalling, .vision, .reasoning],
               contextWindow: 262_000,
               maxOutputTokens: 262_000,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B", displayName: "Nemotron 3 Ultra 550B",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 202_800,
               maxOutputTokens: 202_800,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: ReasoningEffort.none),
               isFullySupported: true, isSeeded: false),
        Record(id: "thinkingmachines/inkling", displayName: "Inkling",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "thinkingmachines/inkling-small", displayName: "Inkling Small",
               capabilities: [.streaming, .toolCalling, .vision, .audio, .reasoning],
               contextWindow: 1_048_576,
               maxOutputTokens: 1_048_576,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .high),
               isFullySupported: true, isSeeded: false),
        Record(id: "openai/gpt-oss-120b", displayName: "OpenAI gpt-oss-120b",
               capabilities: [.streaming, .toolCalling, .reasoning],
               contextWindow: 128_072,
               maxOutputTokens: 128_072,
               reasoningConfig: ModelReasoningConfig(type: .effort, defaultEffort: .medium),
               isFullySupported: true, isSeeded: false),
    ]
}
